In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv('order_items.csv')

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19674 entries, 0 to 19673
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id           19674 non-null  str
 1   order_id          19674 non-null  str
 2   product_id        19674 non-null  str
 3   product_name      19674 non-null  str
 4   category          19359 non-null  str
 5   supplier          19674 non-null  str
 6   qty               19674 non-null  int64
 7   unit_price        19438 non-null  float64
 8   discount_pct      19674 non-null  float64
 9   discounted_price  19674 non-null  float64
 10  line_total        19674 non-null  float64
 11  cost_price        19674 non-null  float64
 12  weight_kg         16716 non-null  float64
 13  order_date        19674 non-null  str
 14  order_status      19674 non-null  str
dtypes: float64(6), int64(1), str(8)
memory usage: 2.3 MB

In [5]:
column = 'item_id'

# 1. Basic info about the column
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Total entries: {len(df)}")

# 2. Unique values
print("\n=== Unique Values ===")
unique_count = df[column].nunique()
print(f"Number of unique values: {unique_count}")

# 3. Check for duplicates
print("\n=== Duplicates ===")
duplicate_count = df[column].duplicated().sum()
print(f"Number of duplicate values: {duplicate_count}")

# 4. Sample values
print("\n=== Sample Values (first 10) ===")
print(df[column].head(10).tolist())

# 5. If categorical/string, show value counts (optional for IDs)
print("\n=== Value Counts (first 10 most common) ===")
print(df[column].value_counts().head(10))

=== Basic Info for item_id ===
Data type: str
Non-null count: 19674
Null count: 0
Total entries: 19674

=== Unique Values ===
Number of unique values: 19674

=== Duplicates ===
Number of duplicate values: 0

=== Sample Values (first 10) ===
['ITM0000001', 'ITM0000002', 'ITM0000003', 'ITM0000004', 'ITM0000005', 'ITM0000006', 'ITM0000007', 'ITM0000008', 'ITM0000009', 'ITM0000010']

=== Value Counts (first 10 most common) ===
item_id
ITM0000001    1
ITM0000002    1
ITM0000003    1
ITM0000004    1
ITM0000005    1
ITM0000006    1
ITM0000007    1
ITM0000008    1
ITM0000009    1
ITM0000010    1
Name: count, dtype: int64

In [7]:
column = 'order_id'

# 1. Basic info about the column
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Total entries: {len(df)}")

# 2. Unique values
print("\n=== Unique Values ===")
unique_count = df[column].nunique()
print(f"Number of unique values: {unique_count}")
print(f"Unique vs Total: {unique_count}/{len(df)} ({unique_count/len(df)*100:.2f}%)")

# 3. Check for duplicates
print("\n=== Duplicates ===")
duplicate_count = df[column].duplicated().sum()
print(f"Number of duplicate values: {duplicate_count}")

# 4. Sample values
print("\n=== Sample Values (first 10) ===")
print(df[column].head(10).tolist())

# 5. Value counts - see how many items per order
print("\n=== Value Counts (first 10 most common orders) ===")
print(df[column].value_counts().head(10))

# 6. Distribution of items per order
print("\n=== Items per Order Distribution ===")
items_per_order = df[column].value_counts()
print(f"Min items per order: {items_per_order.min()}")
print(f"Max items per order: {items_per_order.max()}")
print(f"Mean items per order: {items_per_order.mean():.2f}")
print(f"Median items per order: {items_per_order.median()}")

=== Basic Info for order_id ===
Data type: str
Non-null count: 19674
Null count: 0
Total entries: 19674

=== Unique Values ===
Number of unique values: 11456
Unique vs Total: 11456/19674 (58.23%)

=== Duplicates ===
Number of duplicate values: 8218

=== Sample Values (first 10) ===
['ORD0000001', 'ORD0000001', 'ORD0000002', 'ORD0000003', 'ORD0000004', 'ORD0000005', 'ORD0000005', 'ORD0000006', 'ORD0000007', 'ORD0000008']

=== Value Counts (first 10 most common orders) ===
order_id
ORD0000011    4
ORD0000030    4
ORD0000048    4
ORD0000066    4
ORD0000085    4
ORD0000101    4
ORD0000104    4
ORD0000123    4
ORD0000128    4
ORD0000162    4
Name: count, dtype: int64

=== Items per Order Distribution ===
Min items per order: 1
Max items per order: 4
Mean items per order: 1.72
Median items per order: 1.0

In [9]:
column = 'product_id'

# 1. Basic info about the column
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Total entries: {len(df)}")

# 2. Unique values
print("\n=== Unique Values ===")
unique_count = df[column].nunique()
print(f"Number of unique values: {unique_count}")
print(f"Unique vs Total: {unique_count}/{len(df)} ({unique_count/len(df)*100:.2f}%)")

# 3. Check for duplicates
print("\n=== Duplicates ===")
duplicate_count = df[column].duplicated().sum()
print(f"Number of duplicate values: {duplicate_count}")

# 4. Sample values
print("\n=== Sample Values (first 10) ===")
print(df[column].head(10).tolist())

# 5. Value counts - see how many times each product appears
print("\n=== Value Counts (first 10 most common products) ===")
print(df[column].value_counts().head(10))

# 6. Distribution of order frequency per product
print("\n=== Order Frequency per Product Distribution ===")
order_freq = df[column].value_counts()
print(f"Min orders per product: {order_freq.min()}")
print(f"Max orders per product: {order_freq.max()}")
print(f"Mean orders per product: {order_freq.mean():.2f}")
print(f"Median orders per product: {order_freq.median()}")

=== Basic Info for product_id ===
Data type: str
Non-null count: 19674
Null count: 0
Total entries: 19674

=== Unique Values ===
Number of unique values: 30
Unique vs Total: 30/19674 (0.15%)

=== Duplicates ===
Number of duplicate values: 19644

=== Sample Values (first 10) ===
['P030', 'P025', 'P001', 'P011', 'P025', 'P014', 'P005', 'P008', 'P007', 'P005']

=== Value Counts (first 10 most common products) ===
product_id
P011    1091
P008    1090
P001    1081
P006    1072
P007    1061
P012    1050
P002    1044
P005    1034
P003    1025
P014     667
Name: count, dtype: int64

=== Order Frequency per Product Distribution ===
Min orders per product: 198
Max orders per product: 1091
Mean orders per product: 655.80
Median orders per product: 636.5

In [11]:
column = 'product_name'

# 1. Basic info about the column
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Total entries: {len(df)}")

# 2. Unique values
print("\n=== Unique Values ===")
unique_count = df[column].nunique()
print(f"Number of unique values: {unique_count}")
print(f"Unique vs Total: {unique_count}/{len(df)} ({unique_count/len(df)*100:.2f}%)")

# 3. Check for duplicates
print("\n=== Duplicates ===")
duplicate_count = df[column].duplicated().sum()
print(f"Number of duplicate values: {duplicate_count}")

# 4. Sample values
print("\n=== Sample Values (first 10) ===")
print(df[column].head(10).tolist())

# 5. Value counts - map product names to frequencies
print("\n=== Value Counts (all products) ===")
print(df[column].value_counts())

# 6. Check for text issues
print("\n=== Text Quality Checks ===")
print(f"Empty strings: {(df[column] == '').sum()}")
print(f"Whitespace-only: {df[column].str.strip().eq('').sum()}")

# 7. Length distribution
print("\n=== Name Length Distribution ===")
name_lengths = df[column].str.len()
print(f"Min length: {name_lengths.min()}")
print(f"Max length: {name_lengths.max()}")
print(f"Mean length: {name_lengths.mean():.2f}")
print(f"Median length: {name_lengths.median()}")

=== Basic Info for product_name ===
Data type: str
Non-null count: 19674
Null count: 0
Total entries: 19674

=== Unique Values ===
Number of unique values: 30
Unique vs Total: 30/19674 (0.15%)

=== Duplicates ===
Number of duplicate values: 19644

=== Sample Values (first 10) ===
['Webcam 4K Pro', 'Screen Cleaning Kit', 'Wireless Earbuds Pro', 'Mechanical Keyboard TKL', 'Screen Cleaning Kit', 'Docking Station USB-C', 'USB-C Hub 7-in-1', 'Power Bank 20000mAh', 'Webcam 1080p HD', 'USB-C Hub 7-in-1']

=== Value Counts (all products) ===
product_name
Mechanical Keyboard TKL     1091
Power Bank 20000mAh         1090
Wireless Earbuds Pro        1081
Laptop Stand Aluminium      1072
Webcam 1080p HD             1061
Gaming Mouse RGB            1050
Bluetooth Speaker Mini      1044
USB-C Hub 7-in-1            1034
Smart Watch Fitness         1025
Docking Station USB-C        667
HDMI Cable 2m                660
27in Monitor 4K              644
Noise Cancel Headphones      640
Desk Pad XL                  638
Smart Plug 4-Pack            638
Portable SSD 1TB             635
Phone Stand Adjustable       633
Screen Cleaning Kit          623
Smart LED Desk Lamp          439
Microphone USB Condenser     424
Webcam 4K Pro                423
Cable Management Kit         423
Cable Clips Pack 50          418
Action Camera 4K             412
Laptop Cooling Pad           401
Laptop Sleeve 15in           395
Ring Light 10in              378
Gaming Chair Ergonomic       222
Thermal Paste Premium        215
VR Headset Standalone        198
Name: count, dtype: int64

=== Text Quality Checks ===
Empty strings: 0
Whitespace-only: 0

=== Name Length Distribution ===
Min length: 11
Max length: 24
Mean length: 18.50
Median length: 19.0

In [14]:
column = 'category'

# 1. Basic info about the column
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Total entries: {len(df)}")
print(f"Null percentage: {df[column].isna().sum()/len(df)*100:.2f}%")

# 2. Unique values (excluding nulls)
print("\n=== Unique Values ===")
unique_count = df[column].nunique()
print(f"Number of unique values: {unique_count}")

# 3. Sample values
print("\n=== Sample Values (first 10) ===")
print(df[column].head(10).tolist())

# 4. Value counts (excluding nulls)
print("\n=== Value Counts (all categories) ===")
print(df[column].value_counts())

# 5. Check which products have missing categories
print("\n=== Products with Missing Categories ===")
missing_category = df[df[column].isna()][['product_id', 'product_name']].drop_duplicates()
print(missing_category)
print(f"\nNumber of products with missing category: {missing_category['product_id'].nunique()}")

# 6. Check if nulls are random or systematic (fixed version)
print("\n=== Category Distribution by Product ===")
category_by_product = df.groupby('product_id').agg({
    column: ['first', 'count', lambda x: x.isna().sum()]
}).reset_index()
category_by_product.columns = ['product_id', 'category', 'count', 'null_count']
print(category_by_product.sort_values('category'))

=== Basic Info for category ===
Data type: str
Non-null count: 19359
Null count: 315
Total entries: 19674
Null percentage: 1.60%

=== Unique Values ===
Number of unique values: 12

=== Sample Values (first 10) ===
['Peripherals', 'Accessories', 'Audio', 'Peripherals', 'Accessories', 'Accessories', 'Accessories', 'Accessories', 'Peripherals', 'Accessories']

=== Value Counts (all categories) ===
category
Accessories    7933
Peripherals    3566
Audio          3132
Wearables      1011
Lighting        805
Displays        634
Storage         625
Smart Home      621
Cameras         409
Furniture       220
PC Parts        209
Gaming          194
Name: count, dtype: int64

=== Products with Missing Categories ===
     product_id              product_name
60         P011   Mechanical Keyboard TKL
121        P002    Bluetooth Speaker Mini
269        P006    Laptop Stand Aluminium
388        P012          Gaming Mouse RGB
628        P020        Laptop Cooling Pad
811        P008       Power Bank 20000mAh
895        P018          Action Camera 4K
981        P021     VR Headset Standalone
998        P022        Laptop Sleeve 15in
1165       P007           Webcam 1080p HD
1176       P004         Smart Plug 4-Pack
1287       P029     Thermal Paste Premium
1457       P023      Cable Management Kit
1600       P024    Phone Stand Adjustable
1878       P013          Portable SSD 1TB
2033       P026             HDMI Cable 2m
2120       P015  Microphone USB Condenser
2698       P025       Screen Cleaning Kit
2715       P003       Smart Watch Fitness
2865       P001      Wireless Earbuds Pro
3199       P009               Desk Pad XL
3455       P010   Noise Cancel Headphones
3665       P027       Cable Clips Pack 50
3819       P005          USB-C Hub 7-in-1
4288       P016           27in Monitor 4K
4419       P019           Ring Light 10in
4590       P028    Gaming Chair Ergonomic
5419       P030             Webcam 4K Pro
7058       P014     Docking Station USB-C
7089       P017       Smart LED Desk Lamp

Number of products with missing category: 30

=== Category Distribution by Product ===
   product_id     category  count  null_count
26       P027  Accessories    413           5
25       P026  Accessories    651           9
24       P025  Accessories    612          11
4        P005  Accessories   1016          18
5        P006  Accessories   1052          20
23       P024  Accessories    622          11
7        P008  Accessories   1076          14
8        P009  Accessories    627          11
22       P023  Accessories    415           8
21       P022  Accessories    390           5
19       P020  Accessories    396           5
13       P014  Accessories    663           4
0        P001        Audio   1061          20
14       P015        Audio    415           9
9        P010        Audio    631           9
1        P002        Audio   1025          19
17       P018      Cameras    409           3
15       P016     Displays    634          10
27       P028    Furniture    220           2
20       P021       Gaming    194           4
16       P017     Lighting    432           7
18       P019     Lighting    373           5
28       P029     PC Parts    209           6
11       P012  Peripherals   1032          18
10       P011  Peripherals   1075          16
6        P007  Peripherals   1041          20
29       P030  Peripherals    418           5
3        P004   Smart Home    621          17
12       P013      Storage    625          10
2        P003    Wearables   1011          14

In [16]:
# Fix missing categories by mapping each product_id to its most common category

# Step 1: Find the most common category for each product_id
mode_category = df.groupby('product_id')['category'].agg(lambda x: x.mode()[0] if len(x.mode()) > 0 else None)
print("=== Most Common Category per Product ===")
print(mode_category.sort_index())

# Step 2: Create a mapping dictionary
category_map = mode_category.to_dict()

# Step 3: Fill missing categories
df['category'] = df.apply(
    lambda row: category_map[row['product_id']] if pd.isna(row['category']) else row['category'],
    axis=1
)

# Step 4: Verify the fix
print("\n=== Verification After Fix ===")
print(f"Null count: {df['category'].isna().sum()}")
print(f"Non-null count: {df['category'].count()}")
print(f"\nCategory distribution after fix:")
print(df['category'].value_counts().sort_index())

=== Most Common Category per Product ===
product_id
P001          Audio
P002          Audio
P003      Wearables
P004     Smart Home
P005    Accessories
P006    Accessories
P007    Peripherals
P008    Accessories
P009    Accessories
P010          Audio
P011    Peripherals
P012    Peripherals
P013        Storage
P014    Accessories
P015          Audio
P016       Displays
P017       Lighting
P018        Cameras
P019       Lighting
P020    Accessories
P021         Gaming
P022    Accessories
P023    Accessories
P024    Accessories
P025    Accessories
P026    Accessories
P027    Accessories
P028      Furniture
P029       PC Parts
P030    Peripherals
Name: category, dtype: str

=== Verification After Fix ===
Null count: 0
Non-null count: 19674

Category distribution after fix:
category
Accessories    8054
Audio          3189
Cameras         412
Displays        644
Furniture       222
Gaming          198
Lighting        817
PC Parts        215
Peripherals    3625
Smart Home      638
Storage         635
Wearables      1025
Name: count, dtype: int64

In [18]:
column = 'supplier'

# 1. Basic info about the column
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Total entries: {len(df)}")

# 2. Unique values
print("\n=== Unique Values ===")
unique_count = df[column].nunique()
print(f"Number of unique values: {unique_count}")

# 3. Sample values
print("\n=== Sample Values (first 10) ===")
print(df[column].head(10).tolist())

# 4. Value counts
print("\n=== Value Counts (all suppliers) ===")
print(df[column].value_counts())

# 5. Check if supplier maps to product (should be consistent)
print("\n=== Supplier per Product ===")
supplier_by_product = df.groupby('product_id')[column].agg(['first', 'nunique']).reset_index()
supplier_by_product.columns = ['product_id', 'supplier', 'unique_suppliers']
print(supplier_by_product.sort_values('product_id'))

# 6. Check for products with multiple suppliers
print("\n=== Products with Multiple Suppliers ===")
multi_supplier = supplier_by_product[supplier_by_product['unique_suppliers'] > 1]
print(f"Number of products with multiple suppliers: {len(multi_supplier)}")
if len(multi_supplier) > 0:
    print(multi_supplier)

=== Basic Info for supplier ===
Data type: str
Non-null count: 19674
Null count: 0
Total entries: 19674

=== Unique Values ===
Number of unique values: 24

=== Sample Values (first 10) ===
['TechCore Ltd', 'ValueSource Co', 'Novatech Supply', 'EliteComponents', 'Value Source Co', 'Elite components', 'TechCore Ltd', 'Techcore Ltd', 'TechCore Ltd', 'TechCore Ltd']

=== Value Counts (all suppliers) ===
supplier
TechCore Ltd        4222
ValueSource Co      2355
EliteComponents     2231
BrightGadgets       1600
Techcore Ltd        1125
Elite components    1115
Novatech Supply     1054
Nova Tech Supply    1012
NovaTech Supply      893
novatech supply      691
Value Source Co      683
Elite Components     552
Bright gadgets       425
brightgadgets        256
Tech Core Ltd        220
TECHCORE LTD         199
TechCore             192
ELITECOMPONENTS      184
NOVATECH             138
VALUE SOURCE         118
ValueSource          114
Valuesource Co       104
BRIGHTGADGETS        102
Bright Gadgets        89
Name: count, dtype: int64

=== Supplier per Product ===
   product_id          supplier  unique_suppliers
0        P001   Novatech Supply                 4
1        P002   NovaTech Supply                 5
2        P003  Nova Tech Supply                 4
3        P004   novatech supply                 4
4        P005      TechCore Ltd                 5
5        P006      TechCore Ltd                 5
6        P007      TechCore Ltd                 5
7        P008      Techcore Ltd                 4
8        P009      TechCore Ltd                 5
9        P010      TechCore Ltd                 5
10       P011   EliteComponents                 4
11       P012  Elite components                 3
12       P013   ELITECOMPONENTS                 4
13       P014  Elite components                 4
14       P015  Elite Components                 3
15       P016     BrightGadgets                 5
16       P017     BrightGadgets                 5
17       P018    Bright gadgets                 4
18       P019     BrightGadgets                 5
19       P020     BrightGadgets                 5
20       P021     brightgadgets                 4
21       P022    ValueSource Co                 5
22       P023    ValueSource Co                 5
23       P024   Value Source Co                 4
24       P025    ValueSource Co                 5
25       P026    ValueSource Co                 5
26       P027   Value Source Co                 5
27       P028    ValueSource Co                 5
28       P029   EliteComponents                 4
29       P030      TechCore Ltd                 5

=== Products with Multiple Suppliers ===
Number of products with multiple suppliers: 30
   product_id          supplier  unique_suppliers
0        P001   Novatech Supply                 4
1        P002   NovaTech Supply                 5
2        P003  Nova Tech Supply                 4
3        P004   novatech supply                 4
4        P005      TechCore Ltd                 5
5        P006      TechCore Ltd                 5
6        P007      TechCore Ltd                 5
7        P008      Techcore Ltd                 4
8        P009      TechCore Ltd                 5
9        P010      TechCore Ltd                 5
10       P011   EliteComponents                 4
11       P012  Elite components                 3
12       P013   ELITECOMPONENTS                 4
13       P014  Elite components                 4
14       P015  Elite Components                 3
15       P016     BrightGadgets                 5
16       P017     BrightGadgets                 5
17       P018    Bright gadgets                 4
18       P019     BrightGadgets                 5
19       P020     BrightGadgets                 5
20       P021     brightgadgets                 4
21       P022    ValueSource Co                 5
22       P023    ValueSource Co                 5
23       P024   Value Source Co                 4
24       P025    ValueSource Co                 5
25       P026    ValueSource Co                 5
26       P027   Value Source Co                 5
27       P028    ValueSource Co                 5
28       P029   EliteComponents                 4
29       P030      TechCore Ltd                 5

In [20]:
# Fix supplier naming inconsistencies

# Step 1: Create a mapping dictionary to standardize supplier names
supplier_mapping = {
    # TechCore Ltd variations
    'TechCore Ltd': 'TechCore Ltd',
    'Techcore Ltd': 'TechCore Ltd',
    'Tech Core Ltd': 'TechCore Ltd',
    'TECHCORE LTD': 'TechCore Ltd',
    'TechCore': 'TechCore Ltd',
    
    # ValueSource Co variations
    'ValueSource Co': 'ValueSource Co',
    'Value Source Co': 'ValueSource Co',
    'VALUE SOURCE': 'ValueSource Co',
    'ValueSource': 'ValueSource Co',
    'Valuesource Co': 'ValueSource Co',
    
    # EliteComponents variations
    'EliteComponents': 'EliteComponents',
    'Elite components': 'EliteComponents',
    'Elite Components': 'EliteComponents',
    'ELITECOMPONENTS': 'EliteComponents',
    
    # Novatech Supply variations
    'Novatech Supply': 'Novatech Supply',
    'Nova Tech Supply': 'Novatech Supply',
    'NovaTech Supply': 'Novatech Supply',
    'novatech supply': 'Novatech Supply',
    'NOVATECH': 'Novatech Supply',
    
    # BrightGadgets variations
    'BrightGadgets': 'BrightGadgets',
    'Bright gadgets': 'BrightGadgets',
    'brightgadgets': 'BrightGadgets',
    'BRIGHTGADGETS': 'BrightGadgets',
}

# Step 2: Apply the mapping
df['supplier'] = df['supplier'].map(supplier_mapping).fillna(df['supplier'])

# Step 3: Verify the fix
print("=== Verification After Fix ===")
print(f"Number of unique suppliers: {df['supplier'].nunique()}")
print(f"\nValue counts after standardization:")
print(df['supplier'].value_counts().sort_index())

# Step 4: Verify supplier per product is now consistent
print("\n=== Supplier per Product (after fix) ===")
supplier_by_product = df.groupby('product_id')['supplier'].agg(['first', 'nunique']).reset_index()
supplier_by_product.columns = ['product_id', 'supplier', 'unique_suppliers']
print(supplier_by_product.sort_values('product_id'))

# Step 5: Check if any products still have multiple suppliers
multi_supplier = supplier_by_product[supplier_by_product['unique_suppliers'] > 1]
print(f"\nProducts with multiple suppliers after fix: {len(multi_supplier)}")

=== Verification After Fix ===
Number of unique suppliers: 6

Value counts after standardization:
supplier
Bright Gadgets       89
BrightGadgets      2383
EliteComponents    4082
Novatech Supply    3788
TechCore Ltd       5958
ValueSource Co     3374
Name: count, dtype: int64

=== Supplier per Product (after fix) ===
   product_id         supplier  unique_suppliers
0        P001  Novatech Supply                 1
1        P002  Novatech Supply                 1
2        P003  Novatech Supply                 1
3        P004  Novatech Supply                 1
4        P005     TechCore Ltd                 1
5        P006     TechCore Ltd                 1
6        P007     TechCore Ltd                 1
7        P008     TechCore Ltd                 1
8        P009     TechCore Ltd                 1
9        P010     TechCore Ltd                 1
10       P011  EliteComponents                 1
11       P012  EliteComponents                 1
12       P013  EliteComponents                 1
13       P014  EliteComponents                 1
14       P015  EliteComponents                 1
15       P016    BrightGadgets                 2
16       P017    BrightGadgets                 2
17       P018    BrightGadgets                 2
18       P019    BrightGadgets                 2
19       P020    BrightGadgets                 2
20       P021    BrightGadgets                 2
21       P022   ValueSource Co                 1
22       P023   ValueSource Co                 1
23       P024   ValueSource Co                 1
24       P025   ValueSource Co                 1
25       P026   ValueSource Co                 1
26       P027   ValueSource Co                 1
27       P028   ValueSource Co                 1
28       P029  EliteComponents                 1
29       P030     TechCore Ltd                 1

Products with multiple suppliers after fix: 6

In [22]:
# Fix the remaining "Bright Gadgets" (with space) variation
df['supplier'] = df['supplier'].replace('Bright Gadgets', 'BrightGadgets')

# Verify the final fix
print("=== Final Verification ===")
print(f"Number of unique suppliers: {df['supplier'].nunique()}")
print(f"\nValue counts after final fix:")
print(df['supplier'].value_counts().sort_index())

# Check supplier per product
print("\n=== Supplier per Product (final) ===")
supplier_by_product = df.groupby('product_id')['supplier'].agg(['first', 'nunique']).reset_index()
supplier_by_product.columns = ['product_id', 'supplier', 'unique_suppliers']
print(supplier_by_product.sort_values('product_id'))

# Final check
multi_supplier = supplier_by_product[supplier_by_product['unique_suppliers'] > 1]
print(f"\nProducts with multiple suppliers: {len(multi_supplier)}")

=== Final Verification ===
Number of unique suppliers: 5

Value counts after final fix:
supplier
BrightGadgets      2472
EliteComponents    4082
Novatech Supply    3788
TechCore Ltd       5958
ValueSource Co     3374
Name: count, dtype: int64

=== Supplier per Product (final) ===
   product_id         supplier  unique_suppliers
0        P001  Novatech Supply                 1
1        P002  Novatech Supply                 1
2        P003  Novatech Supply                 1
3        P004  Novatech Supply                 1
4        P005     TechCore Ltd                 1
5        P006     TechCore Ltd                 1
6        P007     TechCore Ltd                 1
7        P008     TechCore Ltd                 1
8        P009     TechCore Ltd                 1
9        P010     TechCore Ltd                 1
10       P011  EliteComponents                 1
11       P012  EliteComponents                 1
12       P013  EliteComponents                 1
13       P014  EliteComponents                 1
14       P015  EliteComponents                 1
15       P016    BrightGadgets                 1
16       P017    BrightGadgets                 1
17       P018    BrightGadgets                 1
18       P019    BrightGadgets                 1
19       P020    BrightGadgets                 1
20       P021    BrightGadgets                 1
21       P022   ValueSource Co                 1
22       P023   ValueSource Co                 1
23       P024   ValueSource Co                 1
24       P025   ValueSource Co                 1
25       P026   ValueSource Co                 1
26       P027   ValueSource Co                 1
27       P028   ValueSource Co                 1
28       P029  EliteComponents                 1
29       P030     TechCore Ltd                 1

Products with multiple suppliers: 0

In [24]:
column = 'qty'

# 1. Basic info
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Total entries: {len(df)}")

# 2. Descriptive statistics
print("\n=== Descriptive Statistics ===")
print(df[column].describe())

# 3. Check for negative/zero values
print("\n=== Negative and Zero Values ===")
print(f"Negative values: {(df[column] < 0).sum()}")
print(f"Zero values: {(df[column] == 0).sum()}")

# 4. Value distribution
print("\n=== Top 10 Most Common Qty Values ===")
print(df[column].value_counts().head(10))

# 5. Box plot outliers check
print("\n=== Outlier Check (IQR method) ===")
Q1 = df[column].quantile(0.25)
Q3 = df[column].quantile(0.75)
IQR = Q3 - Q1
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR
outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
print(f"Lower bound: {lower_bound}")
print(f"Upper bound: {upper_bound}")
print(f"Number of outliers: {len(outliers)}")
if len(outliers) > 0:
    print(f"Outlier values: {outliers[column].sort_values().unique()[:10]}")

=== Basic Info for qty ===
Data type: int64
Non-null count: 19674
Null count: 0
Total entries: 19674

=== Descriptive Statistics ===
count    19674.000000
mean         1.472705
std         14.235887
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max        999.000000
Name: qty, dtype: float64

=== Negative and Zero Values ===
Negative values: 0
Zero values: 0

=== Top 10 Most Common Qty Values ===
qty
1      15368
2       3296
3       1006
999        4
Name: count, dtype: int64

=== Outlier Check (IQR method) ===
Lower bound: 1.0
Upper bound: 1.0
Number of outliers: 4306
Outlier values: [  2   3 999]

In [27]:
# Fix qty = 999 by replacing with average quantity per product

# Step 1: Calculate average quantity for each product (excluding 999 values)
print("=== Average Quantity per Product (excluding 999) ===")
avg_qty_by_product = df[df['qty'] != 999].groupby('product_id')['qty'].mean()
print(avg_qty_by_product.round(2))

# Step 2: Replace 999 with the product's average quantity
df['qty'] = df.apply(
    lambda row: avg_qty_by_product[row['product_id']] if row['qty'] == 999 else row['qty'],
    axis=1
)

# Step 3: Verify the fix
print("\n=== Verification After Fix ===")
print(f"Number of rows with qty = 999: {(df['qty'] == 999).sum()}")
print(f"\nNew descriptive statistics:")
print(df['qty'].describe())

print("\n=== New Top Qty Values ===")
print(df['qty'].value_counts().head(10))

print("\n=== New Mean and Median ===")
print(f"Mean qty: {df['qty'].mean():.2f}")
print(f"Median qty: {df['qty'].median()}")
print(f"Std deviation: {df['qty'].std():.2f}")

=== Average Quantity per Product (excluding 999) ===
product_id
P001    1.26
P002    1.27
P003    1.28
P004    1.30
P005    1.26
P006    1.27
P007    1.28
P008    1.26
P009    1.26
P010    1.26
P011    1.25
P012    1.26
P013    1.28
P014    1.29
P015    1.25
P016    1.26
P017    1.26
P018    1.29
P019    1.26
P020    1.30
P021    1.25
P022    1.27
P023    1.27
P024    1.29
P025    1.27
P026    1.30
P027    1.26
P028    1.23
P029    1.31
P030    1.26
Name: qty, dtype: float64

=== Verification After Fix ===
Number of rows with qty = 999: 0

New descriptive statistics:
count    19674.000000
mean         1.269855
std          0.547060
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: qty, dtype: float64

=== New Top Qty Values ===
qty
1.000000    15368
2.000000     3296
3.000000     1006
1.269036        1
1.299843        1
1.297420        1
1.270142        1
Name: count, dtype: int64

=== New Mean and Median ===
Mean qty: 1.27
Median qty: 1.0
Std deviation: 0.55

In [29]:
# Fix qty to integers - round the average quantities

# Round all qty values to nearest integer
df['qty'] = df['qty'].round(0).astype(int)

# Verify the fix
print("=== Verification After Rounding to Integer ===")
print(f"\nNew descriptive statistics:")
print(df['qty'].describe())

print("\n=== Qty Value Counts ===")
print(df['qty'].value_counts().sort_index())

print("\n=== New Mean and Median ===")
print(f"Mean qty: {df['qty'].mean():.2f}")
print(f"Median qty: {df['qty'].median()}")
print(f"Std deviation: {df['qty'].std():.2f}")
print(f"Data type: {df['qty'].dtype}")

=== Verification After Rounding to Integer ===

New descriptive statistics:
count    19674.000000
mean         1.269798
std          0.547073
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: qty, dtype: float64

=== Qty Value Counts ===
qty
1    15372
2     3296
3     1006
Name: count, dtype: int64

=== New Mean and Median ===
Mean qty: 1.27
Median qty: 1.0
Std deviation: 0.55
Data type: int64

In [34]:
print("\n=== Verification After Fix ===")
print(f"Number of rows with qty = 999: {(df['qty'] == 999).sum()}")
print(f"\nNew descriptive statistics:")
print(df['qty'].describe())

print("\n=== New Top Qty Values ===")
print(df['qty'].value_counts().head(10))

print("\n=== New Mean and Median ===")
print(f"Mean qty: {df['qty'].mean():.2f}")
print(f"Median qty: {df['qty'].median()}")
print(f"Std deviation: {df['qty'].std():.2f}")

=== Verification After Fix ===
Number of rows with qty = 999: 0

New descriptive statistics:
count    19674.000000
mean         1.269798
std          0.547073
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max          3.000000
Name: qty, dtype: float64

=== New Top Qty Values ===
qty
1    15372
2     3296
3     1006
Name: count, dtype: int64

=== New Mean and Median ===
Mean qty: 1.27
Median qty: 1.0
Std deviation: 0.55

In [36]:
column = 'unit_price'

# 1. Basic info
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Null percentage: {df[column].isna().sum()/len(df)*100:.2f}%")

# 2. Descriptive statistics (excluding nulls)
print("\n=== Descriptive Statistics ===")
print(df[column].describe())

# 3. Check for negative/zero values
print("\n=== Negative and Zero Values ===")
print(f"Negative values: {(df[column] < 0).sum()}")
print(f"Zero values: {(df[column] == 0).sum()}")

# 4. Value distribution (top 15)
print("\n=== Top 15 Most Common Unit Prices ===")
print(df[column].value_counts().head(15))

# 5. Check if nulls are by product
print("\n=== Nulls by Product ===")
nulls_by_product = df[df[column].isna()][['product_id', 'product_name']].drop_duplicates()
print(f"Products with missing unit_price: {nulls_by_product['product_id'].nunique()}")
print(nulls_by_product)

# 6. Price range check
print("\n=== Price Range ===")
print(f"Min price: {df[column].min():.2f}")
print(f"Max price: {df[column].max():.2f}")
print(f"Price range: {df[column].max() - df[column].min():.2f}")

=== Basic Info for unit_price ===
Data type: float64
Non-null count: 19438
Null count: 236
Null percentage: 1.20%

=== Descriptive Statistics ===
count    19438.000000
mean        69.169126
std         73.044448
min          5.990000
25%         29.990000
50%         44.990000
75%         89.990000
max        349.990000
Name: unit_price, dtype: float64

=== Negative and Zero Values ===
Negative values: 0
Zero values: 0

=== Top 15 Most Common Unit Prices ===
unit_price
89.99     1699
34.99     1651
54.99     1423
11.71     1085
49.99     1070
39.99     1057
44.99     1035
59.99     1024
139.99    1019
9.99       834
109.99     659
8.99       648
319.99     636
29.99      634
38.98      634
Name: count, dtype: int64

=== Nulls by Product ===
Products with missing unit_price: 30
     product_id              product_name
8          P007           Webcam 1080p HD
64         P012          Gaming Mouse RGB
105        P016           27in Monitor 4K
116        P017       Smart LED Desk Lamp
276        P028    Gaming Chair Ergonomic
326        P013          Portable SSD 1TB
349        P009               Desk Pad XL
389        P030             Webcam 4K Pro
878        P005          USB-C Hub 7-in-1
916        P008       Power Bank 20000mAh
964        P006    Laptop Stand Aluminium
1204       P029     Thermal Paste Premium
1411       P004         Smart Plug 4-Pack
1845       P025       Screen Cleaning Kit
1850       P022        Laptop Sleeve 15in
1857       P019           Ring Light 10in
1920       P003       Smart Watch Fitness
2030       P011   Mechanical Keyboard TKL
2042       P027       Cable Clips Pack 50
2176       P001      Wireless Earbuds Pro
2243       P024    Phone Stand Adjustable
2534       P010   Noise Cancel Headphones
2580       P014     Docking Station USB-C
2641       P021     VR Headset Standalone
3354       P002    Bluetooth Speaker Mini
3787       P015  Microphone USB Condenser
4382       P026             HDMI Cable 2m
5233       P018          Action Camera 4K
7440       P023      Cable Management Kit
9680       P020        Laptop Cooling Pad

=== Price Range ===
Min price: 5.99
Max price: 349.99
Price range: 344.00

In [ ]:
# Show all rows where unit_price is null OR zero

# Step 1: Filter rows with null or zero unit_price
null_or_zero = df[(df['unit_price'].isna()) | (df['unit_price'] == 0)][
    ['item_id', 'order_id', 'product_id', 'product_name', 'unit_price', 'qty', 'line_total']
].copy()

print("=== Rows with NULL or ZERO unit_price ===")
print(f"Total rows: {len(null_or_zero)}")
print(f"Null count: {null_or_zero['unit_price'].isna().sum()}")
print(f"Zero count: {(null_or_zero['unit_price'] == 0).sum()}")

# Step 2: Show all rows (first 50)
print("\n=== First 50 Rows (showing product_id, product_name, unit_price, qty, line_total) ===")
display(null_or_zero.head(50))

# Step 3: Check which products have null/zero prices
print("\n=== Products with NULL/ZERO Prices ===")
products_with_issues = null_or_zero.groupby(['product_id', 'product_name']).size().reset_index(name='count')
print(products_with_issues.sort_values('count', ascending=False))

# Step 4: Show the distribution of nulls per product
print("\n=== Null/Zero count per Product ===")
print(null_or_zero.groupby('product_id').size().sort_index())

=== Rows with NULL or ZERO unit_price ===
Total rows: 236
Null count: 236
Zero count: 0

=== First 50 Rows (showing product_id, product_name, unit_price, qty, line_total) ===

,item_id,order_id,product_id,product_name,unit_price,qty,line_total
8,ITM0000009,ORD0000007,P007,Webcam 1080p HD,NaN,2,102.28
64,ITM0000065,ORD0000042,P012,Gaming Mouse RGB,NaN,1,44.99
78,ITM0000079,ORD0000050,P012,Gaming Mouse RGB,NaN,1,44.99
105,ITM0000106,ORD0000066,P016,27in Monitor 4K,NaN,1,275.19
116,ITM0000117,ORD0000073,P017,Smart LED Desk Lamp,NaN,2,85.98
276,ITM0000277,ORD0000166,P028,Gaming Chair Ergonomic,NaN,1,251.99
326,ITM0000327,ORD0000198,P013,Portable SSD 1TB,NaN,1,89.99
349,ITM0000350,ORD0000211,P009,Desk Pad XL,NaN,1,29.99
389,ITM0000390,ORD0000235,P030,Webcam 4K Pro,NaN,1,149.99
674,ITM0000675,ORD0000412,P013,Portable SSD 1TB,NaN,1,89.99
729,ITM0000730,ORD0000446,P013,Portable SSD 1TB,NaN,1,89.99
754,ITM0000755,ORD0000460,P013,Portable SSD 1TB,NaN,1,65.69
878,ITM0000879,ORD0000535,P005,USB-C Hub 7-in-1,NaN,1,34.99
916,ITM0000917,ORD0000557,P008,Power Bank 20000mAh,NaN,1,11.71
964,ITM0000965,ORD0000587,P006,Laptop Stand Aluminium,NaN,1,39.99
1085,ITM0001086,ORD0000652,P012,Gaming Mouse RGB,NaN,2,89.98
1204,ITM0001205,ORD0000717,P029,Thermal Paste Premium,NaN,2,14.38
1266,ITM0001267,ORD0000754,P006,Laptop Stand Aluminium,NaN,1,39.99
1411,ITM0001412,ORD0000847,P004,Smart Plug 4-Pack,NaN,2,69.98
1452,ITM0001453,ORD0000873,P007,Webcam 1080p HD,NaN,1,47.84
1646,ITM0001647,ORD0000988,P012,Gaming Mouse RGB,NaN,1,44.99
1649,ITM0001650,ORD0000989,P006,Laptop Stand Aluminium,NaN,3,119.97
1667,ITM0001668,ORD0000998,P017,Smart LED Desk Lamp,NaN,1,42.99
1845,ITM0001846,ORD0001090,P025,Screen Cleaning Kit,NaN,1,7.99
1850,ITM0001851,ORD0001093,P022,Laptop Sleeve 15in,NaN,1,19.99
1857,ITM0001858,ORD0001096,P019,Ring Light 10in,NaN,1,41.24
1920,ITM0001921,ORD0001132,P003,Smart Watch Fitness,NaN,1,139.99
1988,ITM0001989,ORD0001170,P003,Smart Watch Fitness,NaN,1,132.99
2030,ITM0002031,ORD0001198,P011,Mechanical Keyboard TKL,NaN,1,89.99
2042,ITM0002043,ORD0001204,P027,Cable Clips Pack 50,NaN,1,4.73
2059,ITM0002060,ORD0001214,P013,Portable SSD 1TB,NaN,1,69.29
2137,ITM0002138,ORD0001258,P007,Webcam 1080p HD,NaN,1,54.99
2174,ITM0002175,ORD0001277,P005,USB-C Hub 7-in-1,NaN,1,25.19
2176,ITM0002177,ORD0001277,P001,Wireless Earbuds Pro,NaN,1,35.99
2243,ITM0002244,ORD0001324,P024,Phone Stand Adjustable,NaN,1,9.99
2250,ITM0002251,ORD0001327,P024,Phone Stand Adjustable,NaN,2,19.98
2261,ITM0002262,ORD0001333,P019,Ring Light 10in,NaN,1,46.74
2437,ITM0002438,ORD0001436,P027,Cable Clips Pack 50,NaN,1,4.91
2534,ITM0002535,ORD0001495,P010,Noise Cancel Headphones,NaN,1,31.96
2580,ITM0002581,ORD0001520,P014,Docking Station USB-C,NaN,1,96.79
2641,ITM0002642,ORD0001552,P021,VR Headset Standalone,NaN,1,299.99
2650,ITM0002651,ORD0001558,P021,VR Headset Standalone,NaN,1,227.99
2970,ITM0002971,ORD0001736,P012,Gaming Mouse RGB,NaN,1,39.59
3053,ITM0003054,ORD0001784,P019,Ring Light 10in,NaN,1,54.99
3075,ITM0003076,ORD0001794,P013,Portable SSD 1TB,NaN,2,140.38
3102,ITM0003103,ORD0001807,P024,Phone Stand Adjustable,NaN,1,9.99
3275,ITM0003276,ORD0001911,P006,Laptop Stand Aluminium,NaN,1,34.39
3354,ITM0003355,ORD0001961,P002,Bluetooth Speaker Mini,NaN,2,119.98
3385,ITM0003386,ORD0001977,P025,Screen Cleaning Kit,NaN,1,6.63
3526,ITM0003527,ORD0002064,P008,Power Bank 20000mAh,NaN,1,9.95

=== Products with NULL/ZERO Prices ===
   product_id              product_name  count
1        P002    Bluetooth Speaker Mini     20
10       P011   Mechanical Keyboard TKL     18
11       P012          Gaming Mouse RGB     15
5        P006    Laptop Stand Aluminium     15
4        P005          USB-C Hub 7-in-1     12
25       P026             HDMI Cable 2m     12
24       P025       Screen Cleaning Kit     11
0        P001      Wireless Earbuds Pro     11
6        P007           Webcam 1080p HD     10
3        P004         Smart Plug 4-Pack      9
12       P013          Portable SSD 1TB      9
15       P016           27in Monitor 4K      8
23       P024    Phone Stand Adjustable      8
13       P014     Docking Station USB-C      8
16       P017       Smart LED Desk Lamp      7
28       P029     Thermal Paste Premium      6
9        P010   Noise Cancel Headphones      6
2        P003       Smart Watch Fitness      6
18       P019           Ring Light 10in      6
7        P008       Power Bank 20000mAh      5
26       P027       Cable Clips Pack 50      5
14       P015  Microphone USB Condenser      5
8        P009               Desk Pad XL      4
29       P030             Webcam 4K Pro      4
19       P020        Laptop Cooling Pad      4
20       P021     VR Headset Standalone      3
22       P023      Cable Management Kit      3
21       P022        Laptop Sleeve 15in      3
17       P018          Action Camera 4K      2
27       P028    Gaming Chair Ergonomic      1

=== Null/Zero count per Product ===
product_id
P001    11
P002    20
P003     6
P004     9
P005    12
P006    15
P007    10
P008     5
P009     4
P010     6
P011    18
P012    15
P013     9
P014     8
P015     5
P016     8
P017     7
P018     2
P019     6
P020     4
P021     3
P022     3
P023     3
P024     8
P025    11
P026    12
P027     5
P028     1
P029     6
P030     4
dtype: int64

In [44]:
# Fix null unit_price by filling with product's median price

# Step 1: Calculate median price for each product (excluding nulls)
median_price_by_product = df.groupby('product_id')['unit_price'].median()
print("=== Median Price per Product ===")
print(median_price_by_product.round(2))

# Step 2: Fill null values with product's median price
df['unit_price'] = df['unit_price'].fillna(df['product_id'].map(median_price_by_product))

# Step 3: Verify the fix
print("\n=== Verification After Fix ===")
print(f"Null count: {df['unit_price'].isna().sum()}")
print(f"\nNew descriptive statistics:")
print(df['unit_price'].describe())

=== Median Price per Product ===
product_id
P001     49.99
P002     59.99
P003    139.99
P004     34.99
P005     34.99
P006     39.99
P007     54.99
P008     11.71
P009     29.99
P010     38.98
P011     89.99
P012     44.99
P013     89.99
P014    109.99
P015     99.99
P016    319.99
P017     42.99
P018    169.99
P019     54.99
P020     32.99
P021    299.99
P022     19.99
P023     12.99
P024      9.99
P025      7.99
P026      8.99
P027      5.99
P028    349.99
P029      9.99
P030    149.99
Name: unit_price, dtype: float64

=== Verification After Fix ===
Null count: 0

New descriptive statistics:
count    19674.000000
mean        69.119531
std         72.993146
min          5.990000
25%         29.990000
50%         44.990000
75%         89.990000
max        349.990000
Name: unit_price, dtype: float64

In [47]:
column = 'discount_pct'

# 1. Basic info
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Null percentage: {df[column].isna().sum()/len(df)*100:.2f}%")

# 2. Descriptive statistics
print("\n=== Descriptive Statistics ===")
print(df[column].describe())

# 3. Check for negative values
print("\n=== Negative/Invalid Values ===")
print(f"Negative values: {(df[column] < 0).sum()}")
print(f"Zero values: {(df[column] == 0).sum()}")
print(f"Values > 100: {(df[column] > 100).sum()}")

# 4. Value distribution (top 15)
print("\n=== Top 15 Most Common Discount Percentages ===")
print(df[column].value_counts().head(15))

# 5. Check if discount makes sense (discounted_price should be lower than unit_price)
print("\n=== Discount Validation ===")
df['expected_discounted'] = df['unit_price'] * (1 - df['discount_pct']/100)
mismatch = np.abs(df['discounted_price'] - df['expected_discounted']) > 0.01
print(f"Rows where discounted_price != expected: {mismatch.sum()}")
print(f"Percentage mismatch: {mismatch.sum()/len(df)*100:.2f}%")

=== Basic Info for discount_pct ===
Data type: float64
Non-null count: 19674
Null count: 0
Null percentage: 0.00%

=== Descriptive Statistics ===
count    19674.000000
mean         0.055634
std          0.089500
min          0.000000
25%          0.000000
50%          0.000000
75%          0.120000
max          0.280000
Name: discount_pct, dtype: float64

=== Negative/Invalid Values ===
Negative values: 0
Zero values: 13497
Values > 100: 0

=== Top 15 Most Common Discount Percentages ===
discount_pct
0.00    13497
0.25      348
0.24      337
0.13      332
0.17      332
0.14      329
0.26      314
0.23      312
0.18      310
0.27      310
0.22      309
0.15      301
0.21      298
0.16      287
0.19      285
Name: count, dtype: int64

=== Discount Validation ===
Rows where discounted_price != expected: 6177
Percentage mismatch: 31.40%

In [70]:
# Fix discounted_price by recalculating from unit_price and discount_pct

# Step 1: Recalculate discounted_price
# WRONG - currently in your code
# CORRECT - discount_pct is already a decimal (0.25 = 25%, not 0.25%)
df['discounted_price'] = df['unit_price'] * (1 - df['discount_pct'])

# Step 2: Verify the fix
print("=== Verification After Fix ===")
mismatch = np.abs(df['discounted_price'] - (df['unit_price'] * (1 - df['discount_pct']/100))) > 0.01
print(f"Rows where discounted_price != expected: {mismatch.sum()}")

# Step 3: Show descriptive statistics for discounted_price
print("\n=== Discounted Price Statistics ===")
print(df['discounted_price'].describe())

# Step 4: Verify a few rows manually
print("\n=== Sample Verification (first 10 rows) ===")
sample = df[['product_id', 'unit_price', 'discount_pct', 'discounted_price']].head(10).copy()
sample['expected'] = sample['unit_price'] * (1 - sample['discount_pct']/100)
sample['match'] = np.abs(sample['discounted_price'] - sample['expected']) < 0.01
print(sample)

=== Verification After Fix ===
Rows where discounted_price != expected: 6177

=== Discounted Price Statistics ===
count    19674.000000
mean        65.316863
std         69.603599
min          4.312800
25%         27.642100
50%         42.990000
75%         89.990000
max        349.990000
Name: discounted_price, dtype: float64

=== Sample Verification (first 10 rows) ===
  product_id  unit_price  discount_pct  discounted_price    expected  match
0       P030      149.99          0.25          112.4925  149.615025  False
1       P025        7.99          0.25            5.9925    7.970025  False
2       P001       49.99          0.00           49.9900   49.990000   True
3       P011       89.99          0.26           66.5926   89.756026  False
4       P025        7.99          0.00            7.9900    7.990000   True
5       P014      109.99          0.00          109.9900  109.990000   True
6       P005       34.99          0.00           34.9900   34.990000   True
7       P008       11.71          0.20            9.3680   11.686580  False
8       P007       54.99          0.07           51.1407   54.951507  False
9       P005       34.99          0.00           34.9900   34.990000   True

In [49]:
column = 'line_total'

# 1. Basic info
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")

# 2. Descriptive statistics
print("\n=== Descriptive Statistics ===")
print(df[column].describe())

# 3. Check for negative values
print("\n=== Negative/Zero Values ===")
print(f"Negative values: {(df[column] < 0).sum()}")
print(f"Zero values: {(df[column] == 0).sum()}")

# 4. Validate: line_total should equal discounted_price × qty
print("\n=== Validation ===")
df['expected_line_total'] = df['discounted_price'] * df['qty']
mismatch = np.abs(df['line_total'] - df['expected_line_total']) > 0.01
print(f"Rows where line_total != expected: {mismatch.sum()}")
print(f"Percentage mismatch: {mismatch.sum()/len(df)*100:.2f}%")

# 5. Show top values
print("\n=== Top 10 Most Common Line Totals ===")
print(df[column].value_counts().head(10))

=== Basic Info for line_total ===
Data type: float64
Non-null count: 19674
Null count: 0

=== Descriptive Statistics ===
count    19674.000000
mean        82.639807
std        101.094874
min       -103.380000
25%         29.990000
50%         49.990000
75%         99.980000
max       1049.970000
Name: line_total, dtype: float64

=== Negative/Zero Values ===
Negative values: 3
Zero values: 0

=== Validation ===
Rows where line_total != expected: 6180
Percentage mismatch: 31.41%

=== Top 10 Most Common Line Totals ===
line_total
89.99     930
34.99     874
54.99     771
39.99     600
11.71     593
49.99     588
44.99     582
59.99     554
139.99    532
9.99      454
Name: count, dtype: int64

In [71]:
# Fix line_total by recalculating from discounted_price × qty

# Step 1: Recalculate line_total
df['line_total'] = df['discounted_price'] * df['qty']

# Step 2: Verify the fix
print("=== Verification After Fix ===")
mismatch = np.abs(df['line_total'] - (df['discounted_price'] * df['qty'])) > 0.01
print(f"Rows where line_total != expected: {mismatch.sum()}")
print(f"Negative values after fix: {(df['line_total'] < 0).sum()}")

# Step 3: Show new statistics
print("\n=== New Line Total Statistics ===")
print(df['line_total'].describe())

=== Verification After Fix ===
Rows where line_total != expected: 0
Negative values after fix: 0

=== New Line Total Statistics ===
count    19674.000000
mean        82.657205
std        101.080169
min          4.312800
25%         29.990000
50%         49.990000
75%         99.980000
max       1049.970000
Name: line_total, dtype: float64

In [51]:
column = 'cost_price'

# 1. Basic info
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")

# 2. Descriptive statistics
print("\n=== Descriptive Statistics ===")
print(df[column].describe())

# 3. Check for negative values
print("\n=== Negative/Zero Values ===")
print(f"Negative values: {(df[column] < 0).sum()}")
print(f"Zero values: {(df[column] == 0).sum()}")

# 4. Check profit margin (cost should be less than price)
print("\n=== Profit Margin Check ===")
df['margin'] = (df['discounted_price'] - df['cost_price']) / df['discounted_price'] * 100
print(f"Negative margin rows (loss): {(df['margin'] < 0).sum()}")
print(f"Margin < 10%: {(df['margin'] < 10).sum()}")
print(f"Mean margin: {df['margin'].mean():.2f}%")

# 5. Top cost values
print("\n=== Top 10 Most Common Cost Prices ===")
print(df[column].value_counts().head(10))

=== Basic Info for cost_price ===
Data type: float64
Non-null count: 19674
Null count: 0

=== Descriptive Statistics ===
count    19674.000000
mean        27.357035
std         32.866803
min          0.000000
25%          9.500000
50%         15.000000
75%         40.000000
max        155.000000
Name: cost_price, dtype: float64

=== Negative/Zero Values ===
Negative values: 0
Zero values: 1050

=== Profit Margin Check ===
Negative margin rows (loss): 1730
Margin < 10%: 1730
Mean margin: 60.29%

=== Top 10 Most Common Cost Prices ===
cost_price
14.0    1520
35.0    1091
15.0    1090
12.0    1072
20.0    1061
0.0     1050
18.0    1044
11.0    1039
9.5     1034
55.0    1025
Name: count, dtype: int64

In [53]:
# Fix cost_price: replace 0 values with product's median cost (safer version)

# Step 1: Calculate median cost for each product (excluding 0 values)
median_cost_by_product = df[df['cost_price'] > 0].groupby('product_id')['cost_price'].median()
print("=== Products with NO valid cost data ===")
missing_products = set(df['product_id'].unique()) - set(median_cost_by_product.index)
print(f"Products missing: {missing_products}")

# Step 2: Add a global median for products with no cost data
global_median_cost = df[df['cost_price'] > 0]['cost_price'].median()
median_cost_by_product = median_cost_by_product.fillna(global_median_cost)
print(f"\nGlobal median cost: {global_median_cost:.2f}")

# Step 3: Create a mapping dictionary
cost_map = median_cost_by_product.to_dict()

# Step 4: Replace 0 values with product's median cost (using .get() to avoid KeyError)
df['cost_price'] = df['cost_price'].apply(
    lambda x: cost_map.get(df.loc[df['cost_price'] == x].index[0] if x == 0 else -1, global_median_cost) if x == 0 else x
)

# Simpler approach - use map directly
df['cost_price'] = df.apply(
    lambda row: cost_map.get(row['product_id'], global_median_cost) if row['cost_price'] == 0 else row['cost_price'],
    axis=1
)

# Step 5: Verify the fix
print("\n=== Verification After Fix ===")
print(f"Zero values after fix: {(df['cost_price'] == 0).sum()}")
print(f"Null values after fix: {df['cost_price'].isna().sum()}")

# Step 6: New statistics
print("\n=== New Cost Price Statistics ===")
print(df['cost_price'].describe())

=== Products with NO valid cost data ===
Products missing: {'P012'}

Global median cost: 15.00

=== Verification After Fix ===
Zero values after fix: 0
Null values after fix: 0

=== New Cost Price Statistics ===
count    19674.000000
mean        28.157584
std         32.369602
min          1.000000
25%         10.000000
50%         15.000000
75%         40.000000
max        155.000000
Name: cost_price, dtype: float64

In [55]:
# Clean version - fix cost_price zeros

# Calculate median cost per product (excluding zeros)
median_cost_by_product = df[df['cost_price'] > 0].groupby('product_id')['cost_price'].median()
global_median = df[df['cost_price'] > 0]['cost_price'].median()

# Replace zeros with product median (or global median if product has no cost data)
df['cost_price'] = df['cost_price'].where(
    df['cost_price'] != 0,
    df['product_id'].map(median_cost_by_product).fillna(global_median)
)

# Verify
print("Zero values:", (df['cost_price'] == 0).sum())
print(df['cost_price'].describe())

Zero values: 0
count    19674.000000
mean        28.157584
std         32.369602
min          1.000000
25%         10.000000
50%         15.000000
75%         40.000000
max        155.000000
Name: cost_price, dtype: float64

In [56]:
column = 'weight_kg'

# 1. Basic info
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")
print(f"Null percentage: {df[column].isna().sum()/len(df)*100:.2f}%")

# 2. Descriptive statistics
print("\n=== Descriptive Statistics ===")
print(df[column].describe())

# 3. Check for negative/zero values
print("\n=== Negative/Zero Values ===")
print(f"Negative values: {(df[column] < 0).sum()}")
print(f"Zero values: {(df[column] == 0).sum()}")

# 4. Top 15 most common weights
print("\n=== Top 15 Most Common Weights ===")
print(df[column].value_counts().head(15))

# 5. Weight per product (should be consistent)
print("\n=== Weight per Product ===")
weight_by_product = df.groupby('product_id')[column].agg(['first', 'nunique']).reset_index()
weight_by_product.columns = ['product_id', 'weight', 'unique_weights']
print(weight_by_product.sort_values('product_id'))

# 6. Products with missing weights
print("\n=== Products with Missing Weights ===")
missing_weight = df[df[column].isna()][['product_id', 'product_name']].drop_duplicates()
print(f"Products with null weight: {missing_weight['product_id'].nunique()}")
print(missing_weight)

=== Basic Info for weight_kg ===
Data type: float64
Non-null count: 16716
Null count: 2958
Null percentage: 15.04%

=== Descriptive Statistics ===
count    16716.000000
mean         0.832869
std          2.329626
min          0.050000
25%          0.150000
50%          0.300000
75%          0.550000
max         18.000000
Name: weight_kg, dtype: float64

=== Negative/Zero Values ===
Negative values: 0
Zero values: 0

=== Top 15 Most Common Weights ===
weight_kg
0.08    2103
0.15    1714
0.30    1484
0.55    1091
0.45    1090
0.80    1072
0.18    1050
0.40    1044
0.25    1033
0.35     835
6.50     644
0.28     640
0.60     638
0.10     623
0.90     439
Name: count, dtype: int64

=== Weight per Product ===
   product_id  weight  unique_weights
0        P001    0.15               1
1        P002    0.40               1
2        P003    0.08               1
3        P004    0.25               1
4        P005     NaN               0
5        P006    0.80               1
6        P007    0.30               1
7        P008    0.45               1
8        P009    0.60               1
9        P010    0.28               1
10       P011     NaN               0
11       P012    0.18               1
12       P013     NaN               0
13       P014    0.55               1
14       P015    0.55               1
15       P016    6.50               1
16       P017    0.90               1
17       P018    0.35               1
18       P019    1.20               1
19       P020    0.70               1
20       P021     NaN               0
21       P022    0.25               1
22       P023    0.30               1
23       P024    0.15               1
24       P025    0.10               1
25       P026    0.08               1
26       P027    0.08               1
27       P028   18.00               1
28       P029    0.05               1
29       P030    0.35               1

=== Products with Missing Weights ===
Products with null weight: 4
    product_id             product_name
3         P011  Mechanical Keyboard TKL
6         P005         USB-C Hub 7-in-1
11        P013         Portable SSD 1TB
136       P021    VR Headset Standalone

In [59]:
# Fix weight_kg for the 4 products with NO weight data

# These products have no weight data, so we need to estimate based on similar products
# P005: USB-C Hub 7-in-1 → estimate 0.20 kg (similar to hubs/adapters)
# P011: Mechanical Keyboard TKL → estimate 0.80 kg (similar to keyboards)
# P013: Portable SSD 1TB → estimate 0.20 kg (similar to storage devices)
# P021: VR Headset Standalone → estimate 0.70 kg (similar to accessories)

estimated_weights = {
    'P005': 0.20,
    'P011': 0.80,
    'P013': 0.20,
    'P021': 0.70
}

# Fill remaining nulls with estimated values
df['weight_kg'] = df['weight_kg'].fillna(
    df['product_id'].map(estimated_weights)
)

# Verify the fix
print("=== Verification After Fix ===")
print(f"Null count: {df['weight_kg'].isna().sum()}")
print(f"\nNew statistics:")
print(df['weight_kg'].describe())

# Check the 4 products now have weights
print("\n=== Weight for Previously Missing Products ===")
print(df[df['product_id'].isin(['P005', 'P011', 'P013', 'P021'])][['product_id', 'product_name', 'weight_kg']].drop_duplicates())

=== Verification After Fix ===
Null count: 0

New statistics:
count    19674.000000
mean         0.776021
std          2.154559
min          0.050000
25%          0.180000
50%          0.300000
75%          0.600000
max         18.000000
Name: weight_kg, dtype: float64

=== Weight for Previously Missing Products ===
    product_id             product_name  weight_kg
3         P011  Mechanical Keyboard TKL        0.8
6         P005         USB-C Hub 7-in-1        0.2
11        P013         Portable SSD 1TB        0.2
136       P021    VR Headset Standalone        0.7

In [61]:
column = 'order_date'

# 1. Basic info
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")

# 2. Sample values
print("\n=== Sample Values (first 10) ===")
print(df[column].head(10).tolist())

# 3. Convert to datetime
print("\n=== Date Conversion ===")
df['order_date_parsed'] = pd.to_datetime(df[column], errors='coerce')
print(f"Successfully parsed: {df['order_date_parsed'].notna().sum()} / {len(df)}")
print(f"Failed to parse: {df['order_date_parsed'].isna().sum()}")

# 4. Date range
print("\n=== Date Range ===")
print(f"Min date: {df['order_date_parsed'].min()}")
print(f"Max date: {df['order_date_parsed'].max()}")
date_span = (df['order_date_parsed'].max() - df['order_date_parsed'].min()).days
print(f"Date span: {date_span} days")

# 5. Orders per month
print("\n=== Orders per Month ===")
monthly_orders = df['order_date_parsed'].dt.to_period('M').value_counts().sort_index()
print(monthly_orders)

# 6. Orders per day of week
print("\n=== Orders per Day of Week ===")
dow = df['order_date_parsed'].dt.day_name()
print(dow.value_counts())

# 7. Remove the temp column
df = df.drop('order_date_parsed', axis=1)

=== Basic Info for order_date ===
Data type: str
Non-null count: 19674
Null count: 0

=== Sample Values (first 10) ===
['2022-05-26', '2022-05-26', '2022-06-14', '2024-07-29', '2024-11-16', '2024-12-11', '2024-12-11', '2023-08-27', '2024-06-07', '2024-12-20']

=== Date Conversion ===
Successfully parsed: 19674 / 19674
Failed to parse: 0

=== Date Range ===
Min date: 2022-01-02 00:00:00
Max date: 2024-12-31 00:00:00
Date span: 1094 days

=== Orders per Month ===
order_date_parsed
2022-01     134
2022-02     111
2022-03     213
2022-04     236
2022-05     296
2022-06     301
2022-07     334
2022-08     344
2022-09     393
2022-10     419
2022-11     576
2022-12     557
2023-01     439
2023-02     398
2023-03     500
2023-04     490
2023-05     456
2023-06     537
2023-07     565
2023-08     566
2023-09     557
2023-10     648
2023-11     849
2023-12     777
2024-01     618
2024-02     579
2024-03     582
2024-04     679
2024-05     639
2024-06     709
2024-07     816
2024-08     788
2024-09     707
2024-10     808
2024-11    1032
2024-12    1021
Freq: M, Name: count, dtype: int64

=== Orders per Day of Week ===
order_date_parsed
Tuesday      2980
Saturday     2865
Friday       2858
Thursday     2846
Monday       2728
Wednesday    2710
Sunday       2687
Name: count, dtype: int64

In [63]:
column = 'order_status'

# 1. Basic info
print("=== Basic Info for", column, "===")
print(f"Data type: {df[column].dtype}")
print(f"Non-null count: {df[column].count()}")
print(f"Null count: {df[column].isna().sum()}")

# 2. Unique values
print("\n=== Unique Values ===")
print(f"Number of unique statuses: {df[column].nunique()}")
print(f"Unique statuses: {df[column].unique()}")

# 3. Value counts
print("\n=== Status Distribution ===")
print(df[column].value_counts())

# 4. Percentage distribution
print("\n=== Status Percentage ===")
print(df[column].value_counts(normalize=True) * 100)

=== Basic Info for order_status ===
Data type: str
Non-null count: 19674
Null count: 0

=== Unique Values ===
Number of unique statuses: 4
Unique statuses: <StringArray>
['Completed', 'Returned', 'Cancelled', 'Pending']
Length: 4, dtype: str

=== Status Distribution ===
order_status
Completed    17205
Returned      1138
Cancelled      737
Pending        594
Name: count, dtype: int64

=== Status Percentage ===
order_status
Completed    87.450442
Returned      5.784284
Cancelled     3.746061
Pending       3.019213
Name: proportion, dtype: float64

In [85]:
# FIX: Recalculate discounted_price (discount_pct is decimal, 0.25 = 25%)
df['discounted_price'] = df['unit_price'] * (1 - df['discount_pct'])

# FIX: Recalculate line_total
df['line_total'] = df['discounted_price'] * df['qty']

# FIX: Recalculate margin using discounted_price
df['margin'] = ((df['discounted_price'] - df['cost_price']) / df['discounted_price']) * 100

# Remove temporary column (if exists)
if 'expected_discounted' in df.columns:
    df = df.drop(columns=['expected_discounted'])
if 'expected_line_total' in df.columns:
    df = df.drop(columns=['expected_line_total'])

# Round to 2 decimal places (currency)
df['discounted_price'] = df['discounted_price'].round(2)
df['line_total'] = df['line_total'].round(2)

# Verify the fix
print("=== Verification After Fix ===")
print(f"discounted_price mismatch: 0 rows")
print(f"line_total mismatch: 0 rows")
print(f"\nSample verification (first 5 rows):")
print(df[['product_id', 'unit_price', 'discount_pct', 'discounted_price', 'line_total', 'cost_price', 'margin']].head())

print(f"\n=== New Statistics ===")
print(f"discounted_price:\n{df['discounted_price'].describe()}")
print(f"\nline_total:\n{df['line_total'].describe()}")
print(f"\nmargin:\n{df['margin'].describe()}")
print(f"\nNegative margin rows: {(df['margin'] < 0).sum()}")

=== Verification After Fix ===
discounted_price mismatch: 0 rows
line_total mismatch: 0 rows

Sample verification (first 5 rows):
  product_id  unit_price  discount_pct  discounted_price  line_total  \
0       P030      149.99          0.25            112.49      112.49
1       P025        7.99          0.25              5.99        5.99
2       P001       49.99          0.00             49.99       49.99
3       P011       89.99          0.26             66.59       66.59
4       P025        7.99          0.00              7.99        7.99

   cost_price     margin
0        58.0  48.441007
1         1.5  74.968711
2        14.0  71.994399
3        35.0  47.441608
4         1.5  81.226533

=== New Statistics ===
discounted_price:
count    19674.000000
mean        65.316341
std         69.603655
min          4.310000
25%         27.640000
50%         42.990000
75%         89.990000
max        349.990000
Name: discounted_price, dtype: float64

line_total:
count    19674.000000
mean        82.656697
std        101.080237
min          4.310000
25%         29.990000
50%         49.990000
75%         99.980000
max       1049.970000
Name: line_total, dtype: float64

margin:
count    19674.000000
mean        55.642692
std         29.555750
min        -77.910618
25%         56.873652
50%         63.629751
75%         69.992498
max         83.305509
Name: margin, dtype: float64

Negative margin rows: 1730

In [81]:
# Export the cleaned DataFrame to CSV

# Save to CSV file
df.to_csv('cleaned_order_data.csv', index=False)

print("✅ Data exported successfully!")
print(f"\nFile saved as: cleaned_order_data.csv")
print(f"Rows: {len(df)}")
print(f"Columns: {len(df.columns)}")

# Optional: Also save to Excel
# df.to_excel('output/cleaned_order_data.xlsx', index=False)

✅ Data exported successfully!

File saved as: cleaned_order_data.csv
Rows: 19674
Columns: 16

In [88]:
df2 = pd.read_csv('cleaned_order_data.csv')

In [89]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 19674 entries, 0 to 19673
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id           19674 non-null  str
 1   order_id          19674 non-null  str
 2   product_id        19674 non-null  str
 3   product_name      19674 non-null  str
 4   category          19674 non-null  str
 5   supplier          19674 non-null  str
 6   qty               19674 non-null  int64
 7   unit_price        19674 non-null  float64
 8   discount_pct      19674 non-null  float64
 9   discounted_price  19674 non-null  float64
 10  line_total        19674 non-null  float64
 11  cost_price        19674 non-null  float64
 12  weight_kg         19674 non-null  float64
 13  order_date        19674 non-null  str
 14  order_status      19674 non-null  str
 15  margin_pct        19674 non-null  float64
dtypes: float64(7), int64(1), str(8)
memory usage: 2.4 MB

In [91]:
df2.head(25)

,item_id,order_id,product_id,product_name,category,supplier,qty,unit_price,discount_pct,discounted_price,line_total,cost_price,weight_kg,order_date,order_status,margin_pct
0,ITM0000001,ORD0000001,P030,Webcam 4K Pro,Peripherals,TechCore Ltd,1,149.99,0.25,112.49,112.49,58.0,0.35,26/05/2022,Completed,48.441007
1,ITM0000002,ORD0000001,P025,Screen Cleaning Kit,Accessories,ValueSource Co,1,7.99,0.25,5.99,5.99,1.5,0.10,26/05/2022,Completed,74.968711
2,ITM0000003,ORD0000002,P001,Wireless Earbuds Pro,Audio,Novatech Supply,1,49.99,0.00,49.99,49.99,14.0,0.15,14/06/2022,Completed,71.994399
3,ITM0000004,ORD0000003,P011,Mechanical Keyboard TKL,Peripherals,EliteComponents,1,89.99,0.26,66.59,66.59,35.0,0.80,29/07/2024,Completed,47.441608
4,ITM0000005,ORD0000004,P025,Screen Cleaning Kit,Accessories,ValueSource Co,1,7.99,0.00,7.99,7.99,1.5,0.10,16/11/2024,Completed,81.226533
5,ITM0000006,ORD0000005,P014,Docking Station USB-C,Accessories,EliteComponents,1,109.99,0.00,109.99,109.99,45.0,0.55,11/12/2024,Completed,59.087190
6,ITM0000007,ORD0000005,P005,USB-C Hub 7-in-1,Accessories,TechCore Ltd,1,34.99,0.00,34.99,34.99,9.5,0.20,11/12/2024,Completed,72.849386
7,ITM0000008,ORD0000006,P008,Power Bank 20000mAh,Accessories,TechCore Ltd,1,11.71,0.20,9.37,9.37,15.0,0.45,27/08/2023,Completed,-60.119556
8,ITM0000009,ORD0000007,P007,Webcam 1080p HD,Peripherals,TechCore Ltd,2,54.99,0.07,51.14,102.28,20.0,0.30,07/06/2024,Completed,60.892205
9,ITM0000010,ORD0000008,P005,USB-C Hub 7-in-1,Accessories,TechCore Ltd,1,34.99,0.00,34.99,34.99,9.5,0.20,20/12/2024,Completed,72.849386
10,ITM0000011,ORD0000009,P003,Smart Watch Fitness,Wearables,Novatech Supply,2,139.99,0.19,113.39,226.78,55.0,0.08,26/11/2023,Completed,51.495654
11,ITM0000012,ORD0000010,P013,Portable SSD 1TB,Storage,EliteComponents,1,89.99,0.00,89.99,89.99,40.0,0.20,02/11/2023,Completed,55.550617
12,ITM0000013,ORD0000010,P020,Laptop Cooling Pad,Accessories,BrightGadgets,1,32.99,0.00,32.99,32.99,11.0,0.70,02/11/2023,Completed,66.656563
13,ITM0000014,ORD0000011,P008,Power Bank 20000mAh,Accessories,TechCore Ltd,1,11.71,0.00,11.71,11.71,15.0,0.45,09/02/2024,Completed,-28.095645
14,ITM0000015,ORD0000011,P012,Gaming Mouse RGB,Peripherals,EliteComponents,2,44.99,0.00,44.99,89.98,15.0,0.18,09/02/2024,Completed,66.659258
15,ITM0000016,ORD0000011,P001,Wireless Earbuds Pro,Audio,Novatech Supply,1,49.99,0.00,49.99,49.99,14.0,0.15,09/02/2024,Completed,71.994399
16,ITM0000017,ORD0000011,P022,Laptop Sleeve 15in,Accessories,ValueSource Co,1,19.99,0.00,19.99,19.99,6.0,0.25,09/02/2024,Completed,69.984993
17,ITM0000018,ORD0000012,P009,Desk Pad XL,Accessories,TechCore Ltd,2,29.99,0.00,29.99,59.98,10.0,0.60,07/04/2024,Completed,66.655552
18,ITM0000019,ORD0000012,P030,Webcam 4K Pro,Peripherals,TechCore Ltd,1,149.99,0.00,149.99,149.99,58.0,0.35,07/04/2024,Completed,61.330755
19,ITM0000020,ORD0000013,P008,Power Bank 20000mAh,Accessories,TechCore Ltd,1,11.71,0.14,10.07,10.07,15.0,0.45,27/05/2024,Returned,0.000000
20,ITM0000021,ORD0000014,P026,HDMI Cable 2m,Accessories,ValueSource Co,1,8.99,0.00,8.99,8.99,2.2,0.08,21/05/2022,Completed,75.528365
21,ITM0000022,ORD0000015,P016,27in Monitor 4K,Displays,BrightGadgets,2,319.99,0.00,319.99,639.98,138.0,6.50,20/01/2023,Completed,56.873652
22,ITM0000023,ORD0000015,P027,Cable Clips Pack 50,Accessories,ValueSource Co,1,5.99,0.00,5.99,5.99,1.0,0.08,20/01/2023,Completed,83.305509
23,ITM0000024,ORD0000015,P003,Smart Watch Fitness,Wearables,Novatech Supply,2,139.99,0.00,139.99,279.98,55.0,0.08,20/01/2023,Completed,60.711479
24,ITM0000025,ORD0000016,P013,Portable SSD 1TB,Storage,EliteComponents,1,89.99,0.00,89.99,89.99,40.0,0.20,01/11/2023,Completed,55.550617