In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('returns.csv')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3791 entries, 0 to 3790
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   return_id      3791 non-null   str
 1   order_id       3791 non-null   str
 2   item_id        3791 non-null   str
 3   product_id     3791 non-null   str
 4   product_name   3791 non-null   str
 5   supplier       3791 non-null   str
 6   category       3731 non-null   str
 7   return_date    3791 non-null   str
 8   return_reason  3670 non-null   str
 9   refund_amount  3791 non-null   float64
 10  qty_returned   3791 non-null   int64
dtypes: float64(1), int64(1), str(9)
memory usage: 325.9 KB

In [8]:
df.head(25)

,return_id,order_id,item_id,product_id,product_name,supplier,category,return_date,return_reason,refund_amount,qty_returned
0,RET000001,ORD0000013,ITM0000020,P008,Power Bank 20000mAh,Techcore Ltd,Accessories,2024-06-07,Defective/Not Working,9.96,1
1,RET000002,ORD0000020,ITM0000031,P007,Webcam 1080p HD,TechCore Ltd,Peripherals,2023-08-09,Defective/Not Working,50.29,1
2,RET000003,ORD0000045,ITM0000068,P019,Ring Light 10in,BrightGadgets,Lighting,2024-03-17,Changed Mind,54.96,1
3,RET000004,ORD0000045,ITM0000069,P011,Mechanical Keyboard TKL,EliteComponents,Peripherals,2024-03-06,Wrong Item Sent,174.35,2
4,RET000005,ORD0000057,ITM0000089,P024,Phone Stand Adjustable,Value Source Co,Accessories,2022-12-16,Wrong Item Sent,7.97,1
5,RET000006,ORD0000057,ITM0000090,P015,Microphone USB Condenser,Elite Components,Audio,2022-12-23,Defective/Not Working,86.55,1
6,RET000007,ORD0000068,ITM0000109,P006,Laptop Stand Aluminium,TechCore Ltd,Accessories,2023-01-06,Defective/Not Working,1414.36,1
7,RET000008,ORD0000068,ITM0000110,P006,Laptop Stand Aluminium,TechCore Ltd,Accessories,2022-12-26,Arrived Damaged,39.03,1
8,RET000009,ORD0000076,ITM0000121,P003,Smart Watch Fitness,Nova Tech Supply,Wearables,2023-06-22,Defective/Not Working,138.50,1
9,RET000010,ORD0000090,ITM0000142,P011,Mechanical Keyboard TKL,EliteComponents,Peripherals,2023-10-02,Wrong Item Sent,80.99,1
10,RET000011,ORD0000109,ITM0000175,P009,Desk Pad XL,TechCore Ltd,Accessories,2022-10-28,Poor Quality,24.11,1
11,RET000012,ORD0000110,ITM0000176,P012,Gaming Mouse RGB,Elite components,Peripherals,2022-12-08,Changed Mind,42.85,1
12,RET000013,ORD0000128,ITM0000207,P029,Thermal Paste Premium,EliteComponents,PC Parts,2024-11-24,Defective/Not Working,9.61,1
13,RET000014,ORD0000128,ITM0000208,P016,27in Monitor 4K,BrightGadgets,Displays,2024-12-10,Changed Mind,950.58,3
14,RET000015,ORD0000128,ITM0000209,P025,Screen Cleaning Kit,ValueSource Co,Accessories,2024-12-12,Defective/Not Working,7.17,1
15,RET000016,ORD0000128,ITM0000210,P014,Docking Station USB-C,EliteComponents,Accessories,2024-12-01,Not as Described,108.95,1
16,RET000017,ORD0000139,ITM0000225,P002,Bluetooth Speaker Mini,NovaTech Supply,Audio,2024-09-05,Defective/Not Working,56.03,1
17,RET000018,ORD0000175,ITM0000292,P016,27in Monitor 4K,BrightGadgets,Displays,2023-06-27,Not as Described,318.63,1
18,RET000019,ORD0000219,ITM0000363,P001,Wireless Earbuds Pro,Novatech Supply,Audio,2023-09-04,NaN,46.61,1
19,RET000020,ORD0000263,ITM0000439,P023,Cable Management Kit,ValueSource Co,Accessories,2024-06-29,Not as Described,9.14,1
20,RET000021,ORD0000284,ITM0000474,P024,Phone Stand Adjustable,Value Source Co,Accessories,2023-09-22,Defective/Not Working,9.52,1
21,RET000022,ORD0000284,ITM0000475,P019,Ring Light 10in,BrightGadgets,Lighting,2023-09-24,Arrived Damaged,49.37,1
22,RET000023,ORD0000301,ITM0000496,P001,Wireless Earbuds Pro,Nova Tech Supply,Audio,2024-04-17,Defective/Not Working,46.48,1
23,RET000024,ORD0000301,ITM0000497,P005,USB-C Hub 7-in-1,TECHCORE LTD,Accessories,2024-04-11,Defective/Not Working,98.79,3
24,RET000025,ORD0000301,ITM0000498,P012,Gaming Mouse RGB,Elite components,Peripherals,2024-04-22,Defective/Not Working,81.06,2

In [10]:
# Check return_id
print("return_id nulls:", df['return_id'].isna().sum())
print("return_id unique:", df['return_id'].nunique())
print("First 5 return_id values:")
print(df['return_id'].head())

# Strip whitespace if any
df['return_id'] = df['return_id'].str.strip()

# Check if all unique (should be)
print("All unique?", df['return_id'].nunique() == len(df))

return_id nulls: 0
return_id unique: 3791
First 5 return_id values:
0    RET000001
1    RET000002
2    RET000003
3    RET000004
4    RET000005
Name: return_id, dtype: str
All unique? True

In [21]:
# print(df["return_id"].to_string(index=False))
df[["return_id"]]

      return_id
0     RET000001
1     RET000002
2     RET000003
3     RET000004
4     RET000005
...         ...
3786  RET003787
3787  RET003788
3788  RET003789
3789  RET003790
3790  RET003791

[3791 rows x 1 columns]

In [22]:
# Check order_id
print("order_id nulls:", df['order_id'].isna().sum())
print("order_id unique:", df['order_id'].nunique())
print("Total rows:", len(df))
print("First 5 order_id values:")
print(df['order_id'].head())

# Strip whitespace if any
df['order_id'] = df['order_id'].str.strip()

# Check if same order_id appears in multiple returns (expected — one order can have multiple returns)
print("\nOrders with multiple returns:")
order_counts = df['order_id'].value_counts()
print(order_counts[order_counts > 1].head(10))

order_id nulls: 0
order_id unique: 3074
Total rows: 3791
First 5 order_id values:
0    ORD0000013
1    ORD0000020
2    ORD0000045
3    ORD0000045
4    ORD0000057
Name: order_id, dtype: str

Orders with multiple returns:
order_id
ORD0000128    4
ORD0000301    4
ORD0000373    4
ORD0000568    4
ORD0000946    4
ORD0001254    4
ORD0001325    4
ORD0001585    4
ORD0001781    4
ORD0001803    4
Name: count, dtype: int64

In [25]:
# print(df["order_id "].to_string(index=False))
df[["order_id"]]

        order_id
0     ORD0000013
1     ORD0000020
2     ORD0000045
3     ORD0000045
4     ORD0000057
...          ...
3786  ORD0011435
3787  ORD0011439
3788  ORD0011440
3789  ORD0011445
3790  ORD0011449

[3791 rows x 1 columns]

In [27]:
# Check item_id
print("item_id nulls:", df['item_id'].isna().sum())
print("item_id unique:", df['item_id'].nunique())
print("Total rows:", len(df))
print("First 5 item_id values:")
print(df['item_id'].head())

# Strip whitespace if any
df['item_id'] = df['item_id'].str.strip()

# Check if item_id is unique
print("\nAll unique?", df['item_id'].nunique() == len(df))

item_id nulls: 0
item_id unique: 3788
Total rows: 3791
First 5 item_id values:
0    ITM0000020
1    ITM0000031
2    ITM0000068
3    ITM0000069
4    ITM0000089
Name: item_id, dtype: str

All unique? False

In [29]:
# Find duplicate item_ids
duplicates = df[df['item_id'].duplicated(keep=False)]
print("Duplicate item_ids:")
print(duplicates[['item_id', 'order_id', 'product_id', 'product_name']])

# If duplicates are truly the same item in different returns, that's OK
# If they're exact row duplicates, we may want to drop them
print("\nExact duplicate rows:", df.duplicated().sum())

Duplicate item_ids:
         item_id    order_id product_id             product_name
1139  ITM0011081  ORD0006489       P003      Smart Watch Fitness
1148  ITM0005148  ORD0003010       P010  Noise Cancel Headphones
1150  ITM0010270  ORD0006008       P008      Power Bank 20000mAh
1843  ITM0005148  ORD0003010       P010  Noise Cancel Headphones
2539  ITM0010270  ORD0006008       P008      Power Bank 20000mAh
2659  ITM0011081  ORD0006489       P003      Smart Watch Fitness

Exact duplicate rows: 0

In [32]:
df[["item_id"]]

         item_id
0     ITM0000020
1     ITM0000031
2     ITM0000068
3     ITM0000069
4     ITM0000089
...          ...
3786  ITM0019652
3787  ITM0019659
3788  ITM0019660
3789  ITM0019668
3790  ITM0019673

[3791 rows x 1 columns]

In [34]:
# Check product_id
print("product_id nulls:", df['product_id'].isna().sum())
print("product_id unique:", df['product_id'].nunique())
print("Total rows:", len(df))
print("First 5 product_id values:")
print(df['product_id'].head())

# Strip whitespace if any
df['product_id'] = df['product_id'].str.strip()

# Check if product_id is unique
print("\nAll unique?", df['product_id'].nunique() == len(df))

# Show product_id value counts (how many times each product appears)
print("\nTop 10 product_id counts:")
print(df['product_id'].value_counts().head(10))

product_id nulls: 0
product_id unique: 30
Total rows: 3791
First 5 product_id values:
0    P008
1    P007
2    P019
3    P011
4    P024
Name: product_id, dtype: str

All unique? False

Top 10 product_id counts:
product_id
P002    528
P001    511
P004    301
P003    164
P006    142
P012    142
P008    139
P007    133
P005    130
P026    125
Name: count, dtype: int64

In [36]:
df['product_id']

0       P008
1       P007
2       P019
3       P011
4       P024
        ...
3786    P001
3787    P002
3788    P004
3789    P013
3790    P024
Name: product_id, Length: 3791, dtype: str

In [38]:
# Check product_name
print("product_name nulls:", df['product_name'].isna().sum())
print("product_name unique:", df['product_name'].nunique())
print("Total rows:", len(df))
print("First 5 product_name values:")
print(df['product_name'].head())

# Strip whitespace
df['product_name'] = df['product_name'].str.strip()

# Check if product_name matches product_id consistently
print("\nProduct name vs product_id mapping (top 10):")
print(df.groupby(['product_id', 'product_name']).size().head(10))

# Check if any product_id has multiple product names (inconsistency)
print("\nProduct IDs with multiple names:")
multiple_names = df.groupby('product_id')['product_name'].nunique()
print(multiple_names[multiple_names > 1])

product_name nulls: 0
product_name unique: 30
Total rows: 3791
First 5 product_name values:
0        Power Bank 20000mAh
1            Webcam 1080p HD
2            Ring Light 10in
3    Mechanical Keyboard TKL
4     Phone Stand Adjustable
Name: product_name, dtype: str

Product name vs product_id mapping (top 10):
product_id  product_name
P001        Wireless Earbuds Pro       511
P002        Bluetooth Speaker Mini     528
P003        Smart Watch Fitness        164
P004        Smart Plug 4-Pack          301
P005        USB-C Hub 7-in-1           130
P006        Laptop Stand Aluminium     142
P007        Webcam 1080p HD            133
P008        Power Bank 20000mAh        139
P009        Desk Pad XL                 76
P010        Noise Cancel Headphones     90
dtype: int64

Product IDs with multiple names:
Series([], Name: product_name, dtype: int64)

In [40]:
df['product_name']

0           Power Bank 20000mAh
1               Webcam 1080p HD
2               Ring Light 10in
3       Mechanical Keyboard TKL
4        Phone Stand Adjustable
                 ...
3786       Wireless Earbuds Pro
3787     Bluetooth Speaker Mini
3788          Smart Plug 4-Pack
3789           Portable SSD 1TB
3790     Phone Stand Adjustable
Name: product_name, Length: 3791, dtype: str

In [41]:
# Check supplier
print("supplier nulls:", df['supplier'].isna().sum())
print("supplier unique:", df['supplier'].nunique())
print("First 10 supplier values:")
print(df['supplier'].head(10))

# Check case variations
print("\nSupplier value counts (lowercased, top 15):")
print(df['supplier'].str.lower().value_counts().head(15))

supplier nulls: 0
supplier unique: 24
First 10 supplier values:
0        Techcore Ltd
1        TechCore Ltd
2       BrightGadgets
3     EliteComponents
4     Value Source Co
5    Elite Components
6        TechCore Ltd
7        TechCore Ltd
8    Nova Tech Supply
9     EliteComponents
Name: supplier, dtype: str

Supplier value counts (lowercased, top 15):
supplier
novatech supply     1361
techcore ltd         699
valuesource co       519
brightgadgets        333
elitecomponents      270
elite components     228
nova tech supply     132
value source co       98
bright gadgets        58
techcore              30
tech core ltd         26
valuesource           14
value source          12
novatech              11
Name: count, dtype: int64

In [42]:
# Clean supplier names
df['supplier'] = df['supplier'].str.strip().str.lower()

supplier_map = {
    'techcore ltd': 'TechCore Ltd',
    'techcoreltd': 'TechCore Ltd',
    'techcore': 'TechCore Ltd',
    'tech core ltd': 'TechCore Ltd',
    'elitecomponents': 'EliteComponents',
    'elite components': 'EliteComponents',
    'novatech supply': 'NovaTech Supply',
    'nova tech supply': 'NovaTech Supply',
    'novatechsupply': 'NovaTech Supply',
    'value source co': 'ValueSource Co',
    'valuesource co': 'ValueSource Co',
    'valuesourceco': 'ValueSource Co',
    'value source': 'ValueSource Co',
    'valuesource': 'ValueSource Co',
    'brightgadgets': 'BrightGadgets',
    'bright gadgets': 'BrightGadgets'
}

df['supplier'] = df['supplier'].map(supplier_map).fillna(df['supplier'].str.title())

# Verify cleaning
print("Cleaned supplier value counts:")
print(df['supplier'].value_counts())

Cleaned supplier value counts:
supplier
NovaTech Supply    1493
TechCore Ltd        755
ValueSource Co      643
EliteComponents     498
BrightGadgets       391
Novatech             11
Name: count, dtype: int64

In [43]:
# Fix remaining Novatech variation
df['supplier'] = df['supplier'].replace('Novatech', 'NovaTech Supply')

# Verify final cleaning
print("Final supplier value counts:")
print(df['supplier'].value_counts())
print("\nUnique suppliers:", df['supplier'].nunique())

Final supplier value counts:
supplier
NovaTech Supply    1504
TechCore Ltd        755
ValueSource Co      643
EliteComponents     498
BrightGadgets       391
Name: count, dtype: int64

Unique suppliers: 5

In [45]:
# Check category
print("category nulls:", df['category'].isna().sum())
print("category unique:", df['category'].nunique())
print("First 10 category values:")
print(df['category'].head(10))

# Show value counts (excluding NaN)
print("\nCategory value counts:")
print(df['category'].value_counts(dropna=True))

category nulls: 60
category unique: 12
First 10 category values:
0    Accessories
1    Peripherals
2       Lighting
3    Peripherals
4    Accessories
5          Audio
6    Accessories
7    Accessories
8      Wearables
9    Peripherals
Name: category, dtype: str

Category value counts:
category
Accessories    1189
Audio          1162
Peripherals     430
Smart Home      291
Wearables       162
Lighting        137
Displays        107
Storage          78
Furniture        57
Cameras          49
Gaming           38
PC Parts         31
Name: count, dtype: int64

In [49]:
print(df['category'].to_string(index=False))

Accessories
Peripherals
   Lighting
Peripherals
Accessories
      Audio
Accessories
Accessories
  Wearables
Peripherals
Accessories
Peripherals
   PC Parts
   Displays
Accessories
Accessories
      Audio
   Displays
      Audio
Accessories
Accessories
   Lighting
      Audio
Accessories
Peripherals
Peripherals
Accessories
  Wearables
Accessories
Peripherals
Peripherals
   Displays
Peripherals
Peripherals
Accessories
  Wearables
   Displays
      Audio
Accessories
   Lighting
Accessories
      Audio
Accessories
Peripherals
      Audio
  Wearables
Peripherals
  Furniture
Accessories
      Audio
    Cameras
    Storage
Accessories
      Audio
Peripherals
    Storage
      Audio
Accessories
Accessories
Accessories
Accessories
Accessories
Accessories
Accessories
     Gaming
      Audio
Accessories
   PC Parts
  Furniture
Accessories
      Audio
Accessories
   PC Parts
Accessories
Accessories
Peripherals
Accessories
      Audio
  Wearables
      Audio
Peripherals
Accessories
Accessories
Peripherals
Accessories
Accessories
      Audio
  Wearables
Accessories
Peripherals
Accessories
Peripherals
Accessories
   Displays
Accessories
Peripherals
    Storage
Accessories
Accessories
      Audio
Peripherals
    Cameras
Peripherals
  Wearables
Accessories
Accessories
Peripherals
 Smart Home
Peripherals
Peripherals
Accessories
Accessories
Accessories
      Audio
Accessories
Accessories
    Storage
      Audio
Accessories
  Wearables
Accessories
      Audio
Accessories
Accessories
   PC Parts
  Wearables
Peripherals
      Audio
      Audio
Accessories
Accessories
Accessories
   PC Parts
Peripherals
Peripherals
      Audio
Accessories
   Lighting
  Wearables
Accessories
      Audio
Accessories
Accessories
   Displays
  Wearables
Accessories
      Audio
Peripherals
   Displays
  Wearables
      Audio
Accessories
Accessories
   Lighting
 Smart Home
Accessories
Accessories
Accessories
      Audio
      Audio
Accessories
Accessories
    Storage
Accessories
      Audio
Accessories
        NaN
Peripherals
      Audio
Accessories
Peripherals
Accessories
Peripherals
    Storage
    Storage
Peripherals
Peripherals
Peripherals
      Audio
      Audio
      Audio
      Audio
  Wearables
Peripherals
Accessories
Accessories
  Wearables
      Audio
Accessories
Accessories
Peripherals
Accessories
      Audio
      Audio
Accessories
    Storage
 Smart Home
      Audio
Accessories
      Audio
      Audio
Accessories
  Wearables
   Displays
   Lighting
Accessories
Peripherals
Accessories
  Wearables
Peripherals
Accessories
Peripherals
Accessories
      Audio
Peripherals
Accessories
      Audio
    Cameras
      Audio
    Cameras
  Wearables
Accessories
 Smart Home
      Audio
Accessories
Peripherals
Peripherals
      Audio
      Audio
Peripherals
      Audio
Peripherals
Accessories
Peripherals
Accessories
  Wearables
Accessories
 Smart Home
  Wearables
  Wearables
    Cameras
Accessories
Accessories
 Smart Home
  Furniture
      Audio
      Audio
      Audio
Peripherals
Accessories
Accessories
      Audio
Peripherals
      Audio
Peripherals
Accessories
      Audio
   Lighting
Accessories
   PC Parts
Accessories
      Audio
Accessories
Peripherals
   Lighting
Accessories
  Wearables
        NaN
Peripherals
Accessories
Peripherals
Accessories
      Audio
Accessories
Accessories
Accessories
      Audio
  Wearables
    Storage
Accessories
Peripherals
   Lighting
Accessories
  Furniture
      Audio
Accessories
Peripherals
   Lighting
      Audio
  Wearables
   Displays
Accessories
      Audio
      Audio
  Wearables
Accessories
      Audio
Accessories
Accessories
  Furniture
 Smart Home
    Storage
Peripherals
Accessories
      Audio
      Audio
    Cameras
Accessories
   Displays
Accessories
Accessories
        NaN
  Wearables
Accessories
   PC Parts
Accessories
    Storage
Accessories
Accessories
   Lighting
Accessories
Peripherals
      Audio
Accessories
Accessories
Peripherals
Peripherals
      Audio
 Smart Home
   Lighting
 Smart Home
Accessories
Peripherals
Accessories
      Audio
  Wearables
Accessories
    Storage
  Wearables
Accessories
Peripherals
Accessories
Peripherals
Peripherals
Accessories
Peripherals
Peripherals
Accessories
Accessories
Peripherals
Accessories
    Storage
Peripherals
Accessories
Accessories
      Audio
 Smart Home
Accessories
  Wearables
Accessories
   Lighting
  Furniture
  Wearables
  Furniture
Accessories
Accessories
Peripherals
      Audio
  Furniture
  Furniture
Peripherals
Accessories
   PC Parts
Accessories
   Lighting
Accessories
 Smart Home
  Furniture
Accessories
 Smart Home
      Audio
Accessories
    Storage
      Audio
Accessories
Accessories
      Audio
      Audio
   Lighting
      Audio
Accessories
Accessories
      Audio
      Audio
     Gaming
Accessories
Accessories
Accessories
Accessories
        NaN
    Storage
Accessories
Accessories
Peripherals
    Storage
      Audio
Peripherals
Accessories
Accessories
Accessories
   Lighting
Accessories
Peripherals
Peripherals
     Gaming
Accessories
Accessories
  Wearables
Peripherals
Peripherals
      Audio
Accessories
   Displays
  Wearables
  Wearables
      Audio
Accessories
Accessories
      Audio
Accessories
Accessories
Accessories
   Lighting
Accessories
Accessories
 Smart Home
    Storage
    Cameras
Accessories
Peripherals
Accessories
Accessories
Peripherals
    Cameras
    Cameras
Accessories
      Audio
  Wearables
Accessories
  Wearables
     Gaming
Peripherals
      Audio
      Audio
      Audio
   Lighting
Accessories
Accessories
Accessories
 Smart Home
     Gaming
Accessories
    Cameras
Peripherals
 Smart Home
Accessories
Accessories
Accessories
    Storage
    Cameras
Accessories
      Audio
Peripherals
Accessories
Accessories
      Audio
Accessories
Accessories
   Lighting
Accessories
  Wearables
Peripherals
Accessories
Peripherals
Accessories
Accessories
    Storage
Peripherals
      Audio
    Storage
Accessories
Accessories
Peripherals
Accessories
      Audio
Peripherals
Accessories
Accessories
      Audio
Accessories
      Audio
   Lighting
      Audio
    Storage
Peripherals
   Lighting
    Storage
Accessories
    Storage
Peripherals
Accessories
   PC Parts
Peripherals
Accessories
Accessories
      Audio
Accessories
     Gaming
Peripherals
Accessories
 Smart Home
Peripherals
Peripherals
Accessories
Accessories
Accessories
Accessories
Accessories
Peripherals
  Wearables
Accessories
Accessories
Accessories
Peripherals
 Smart Home
Peripherals
Accessories
      Audio
Peripherals
Accessories
Accessories
Peripherals
  Wearables
      Audio
Peripherals
  Wearables
Peripherals
 Smart Home
        NaN
Accessories
Accessories
Accessories
Accessories
Accessories
Peripherals
      Audio
Accessories
Peripherals
  Wearables
      Audio
Accessories
  Furniture
Peripherals
Accessories
Accessories
    Cameras
Accessories
   Lighting
Accessories
Peripherals
Accessories
      Audio
 Smart Home
Accessories
  Wearables
Accessories
Accessories
Accessories
Peripherals
      Audio
Peripherals
Accessories
   Lighting
    Storage
Accessories
        NaN
Accessories
Peripherals
Accessories
Accessories
Peripherals
Accessories
Peripherals
   Lighting
Accessories
Accessories
      Audio
  Wearables
Accessories
   Lighting
    Cameras
Accessories
Peripherals
Accessories
Accessories
Peripherals
Peripherals
Accessories
      Audio
    Cameras
      Audio
Accessories
    Storage
Accessories
   Lighting
    Storage
Accessories
  Wearables
Accessories
Peripherals
Peripherals
      Audio
      Audio
      Audio
   Lighting
Peripherals
Accessories
Accessories
      Audio
Accessories
Accessories
Accessories
    Cameras
Peripherals
      Audio
   Lighting
Accessories
      Audio
    Storage
Peripherals
Peripherals
Accessories
Accessories
Peripherals
    Storage
Peripherals
Accessories
Accessories
Accessories
Accessories
      Audio
      Audio
Accessories
Peripherals
Accessories
  Furniture
  Wearables
      Audio
   Displays
Accessories
Accessories
      Audio
      Audio
      Audio
Peripherals
  Wearables
Peripherals
Peripherals
Accessories
Peripherals
Accessories
Accessories
Accessories
Accessories
Peripherals
Peripherals
Accessories
Peripherals
Accessories
Peripherals
      Audio
   Lighting
        NaN
      Audio
Accessories
   Lighting
Accessories
   Lighting
Peripherals
      Audio
Accessories
Accessories
  Furniture
Accessories
Accessories
   Displays
Accessories
Accessories
  Wearables
Peripherals
Accessories
Accessories
Accessories
Peripherals
      Audio
Peripherals
Accessories
Peripherals
Accessories
      Audio
Peripherals
Peripherals
Accessories
Accessories
Peripherals
Accessories
      Audio
Accessories
   Displays
     Gaming
Accessories
Peripherals
Peripherals
Peripherals
Accessories
Accessories
      Audio
Accessories
      Audio
     Gaming
Accessories
      Audio
  Furniture
      Audio
     Gaming
Accessories
   Displays
  Furniture
Accessories
        NaN
Peripherals
Accessories
  Furniture
        NaN
        NaN
      Audio
    Storage
Peripherals
Accessories
Peripherals
Accessories
Accessories
Accessories
   PC Parts
Accessories
Accessories
   Lighting
Peripherals
Accessories
      Audio
Accessories
Accessories
      Audio
Accessories
      Audio
Accessories
Accessories
Peripherals
 Smart Home
Accessories
Accessories
Accessories
   Lighting
Accessories
      Audio
     Gaming
Peripherals
Accessories
Peripherals
Accessories
 Smart Home
   Displays
Accessories
Peripherals
   Lighting
Accessories
Accessories
Accessories
Accessories
Peripherals
Accessories
   Displays
Peripherals
      Audio
    Storage
Peripherals
 Smart Home
Accessories
   Lighting
Peripherals
Accessories
Accessories
Peripherals
   Displays
Accessories
      Audio
   Displays
      Audio
      Audio
Peripherals
Accessories
Accessories
      Audio
 Smart Home
      Audio
Accessories
Accessories
Accessories
Accessories
Accessories
Accessories
Accessories
      Audio
Accessories
Accessories
Accessories
      Audio
Accessories
      Audio
  Wearables
Accessories
Accessories
Peripherals
Peripherals
      Audio
      Audio
    Storage
      Audio
    Cameras
  Wearables
Peripherals
  Wearables
Accessories
Accessories
      Audio
Accessories
Accessories
Accessories
Accessories
Peripherals
 Smart Home
   Displays
Peripherals
Accessories
Peripherals
Accessories
Peripherals
      Audio
    Storage
Accessories
Accessories
  Furniture
Accessories
Peripherals
Accessories
Accessories
Peripherals
Accessories
  Furniture
    Storage
      Audio
      Audio
Accessories
Accessories
 Smart Home
  Furniture
Accessories
   Lighting
Peripherals
Accessories
Accessories
    Storage
Accessories
        NaN
Accessories
Peripherals
      Audio
   Lighting
Accessories
      Audio
   Displays
Peripherals
Peripherals
Peripherals
Accessories
Accessories
    Cameras
Accessories
Accessories
  Wearables
   Lighting
Peripherals
Accessories
  Wearables
Accessories
Accessories
Accessories
Accessories
      Audio
Peripherals
    Storage
Accessories
Accessories
      Audio
Accessories
Accessories
      Audio
Peripherals
      Audio
      Audio
Accessories
      Audio
   Displays
      Audio
    Storage
Accessories
Accessories
Accessories
Accessories
Accessories
Accessories
Peripherals
Accessories
Peripherals
Peripherals
Accessories
Peripherals
Accessories
Accessories
Peripherals
      Audio
      Audio
Accessories
Peripherals
Peripherals
      Audio
  Wearables
Accessories
      Audio
  Wearables
Accessories
  Wearables
        NaN
Accessories
Accessories
   Lighting
 Smart Home
Accessories
      Audio
      Audio
    Cameras
   Displays
Peripherals
Peripherals
 Smart Home
      Audio
      Audio
  Wearables
Accessories
Accessories
Accessories
Peripherals
Peripherals
    Storage
    Storage
      Audio
Accessories
Accessories
  Wearables
Accessories
      Audio
Peripherals
Peripherals
Accessories
Accessories
      Audio
  Wearables
Accessories
  Wearables
      Audio
Peripherals
      Audio
Accessories
  Wearables
Peripherals
      Audio
   Displays
      Audio
Accessories
Accessories
    Cameras
Accessories
Accessories
Accessories
Accessories
Peripherals
   PC Parts
Accessories
Accessories
      Audio
Peripherals
      Audio
Accessories
      Audio
Accessories
Peripherals
Accessories
      Audio
Accessories
  Wearables
      Audio
      Audio
Peripherals
      Audio
    Storage
      Audio
Peripherals
   PC Parts
Peripherals
      Audio
Accessories
      Audio
Peripherals
   Lighting
Accessories
    Storage
Accessories
      Audio
Peripherals
      Audio
Peripherals
  Wearables
Peripherals
Accessories
Accessories
    Cameras
Accessories
      Audio
Peripherals
   Displays
Peripherals
Peripherals
Accessories
      Audio
Peripherals
    Cameras
 Smart Home
Peripherals
    Cameras
Accessories
Accessories
   Displays
Accessories
Peripherals
Accessories
Accessories
      Audio
Accessories
   Displays
  Wearables
      Audio
      Audio
      Audio
Peripherals
Accessories
    Storage
      Audio
Accessories
      Audio
Peripherals
    Cameras
   Lighting
      Audio
Peripherals
Accessories
      Audio
      Audio
Accessories
Accessories
Peripherals
      Audio
Accessories
        NaN
Peripherals
Accessories
Peripherals
        NaN
      Audio
    Cameras
      Audio
Peripherals
Peripherals
        NaN
Peripherals
   Lighting
      Audio
Accessories
Accessories
Accessories
Peripherals
      Audio
Accessories
      Audio
Accessories
Accessories
      Audio
    Storage
      Audio
Accessories
Accessories
Accessories
   Lighting
 Smart Home
Accessories
Accessories
Accessories
Peripherals
    Storage
Peripherals
Accessories
      Audio
Accessories
Accessories
Peripherals
Accessories
Accessories
Accessories
      Audio
Accessories
  Wearables
Accessories
Accessories
  Wearables
Accessories
Peripherals
   PC Parts
    Cameras
Peripherals
      Audio
Accessories
Accessories
      Audio
Accessories
Accessories
      Audio
   Displays
   Lighting
Accessories
  Furniture
   Displays
      Audio
      Audio
Peripherals
      Audio
 Smart Home
        NaN
    Storage
 Smart Home
Accessories
    Storage
Accessories
      Audio
      Audio
      Audio
      Audio
      Audio
Accessories
      Audio
Peripherals
Accessories
      Audio
 Smart Home
 Smart Home
      Audio
      Audio
    Storage
Accessories
Accessories
  Furniture
      Audio
      Audio
   Displays
      Audio
Accessories
   Lighting
Accessories
Accessories
 Smart Home
   Lighting
Peripherals
 Smart Home
      Audio
      Audio
Peripherals
      Audio
      Audio
Accessories
      Audio
      Audio
   PC Parts
Accessories
      Audio
   Displays
Accessories
Accessories
Accessories
Accessories
Accessories
Accessories
Accessories
Accessories
      Audio
Accessories
      Audio
Peripherals
      Audio
      Audio
      Audio
      Audio
Accessories
Accessories
Accessories
      Audio
      Audio
      Audio
      Audio
Accessories
      Audio
Accessories
Accessories
Accessories
      Audio
Accessories
        NaN
 Smart Home
Accessories
Accessories
Accessories
  Furniture
      Audio
  Wearables
Accessories
   PC Parts
      Audio
Accessories
   Lighting
      Audio
      Audio
      Audio
    Cameras
      Audio
  Wearables
Accessories
      Audio
  Wearables
      Audio
Accessories
Accessories
      Audio
      Audio
      Audio
      Audio
      Audio
Accessories
Accessories
      Audio
 Smart Home
Accessories
 Smart Home
      Audio
      Audio
Peripherals
Accessories
Peripherals
      Audio
      Audio
Accessories
Accessories
      Audio
   Displays
      Audio
  Wearables
Accessories
Peripherals
Accessories
   Displays
      Audio
Peripherals
  Furniture
Peripherals
   Lighting
        NaN
        NaN
      Audio
Accessories
Accessories
Accessories
     Gaming
Accessories
      Audio
      Audio
 Smart Home
      Audio
Accessories
      Audio
      Audio
Accessories
  Furniture
      Audio
      Audio
Accessories
Accessories
  Wearables
 Smart Home
   PC Parts
Accessories
Accessories
Peripherals
Accessories
Accessories
      Audio
Accessories
Accessories
Accessories
      Audio
      Audio
 Smart Home
   Displays
Peripherals
Peripherals
Peripherals
      Audio
 Smart Home
      Audio
      Audio
      Audio
        NaN
      Audio
  Wearables
      Audio
      Audio
      Audio
 Smart Home
Accessories
Peripherals
Accessories
      Audio
Accessories
Peripherals
      Audio
 Smart Home
 Smart Home
Accessories
Accessories
Accessories
      Audio
      Audio
Accessories
      Audio
Accessories
Peripherals
      Audio
 Smart Home
Accessories
Peripherals
      Audio
Peripherals
 Smart Home
   Lighting
Peripherals
      Audio
Peripherals
   Displays
Peripherals
Peripherals
      Audio
   Lighting
Accessories
Accessories
Accessories
 Smart Home
Accessories
      Audio
Accessories
Accessories
Accessories
 Smart Home
Peripherals
      Audio
      Audio
        NaN
   Lighting
Accessories
      Audio
   Lighting
Peripherals
      Audio
Accessories
      Audio
        NaN
Accessories
Accessories
  Wearables
 Smart Home
Accessories
      Audio
Accessories
   Lighting
      Audio
    Cameras
Peripherals
 Smart Home
   Lighting
  Wearables
   Lighting
      Audio
      Audio
  Furniture
Accessories
Peripherals
      Audio
        NaN
Accessories
 Smart Home
Accessories
      Audio
      Audio
      Audio
      Audio
  Wearables
 Smart Home
      Audio
      Audio
Accessories
      Audio
      Audio
 Smart Home
      Audio
      Audio
      Audio
Peripherals
      Audio
        NaN
  Furniture
Accessories
    Storage
      Audio
      Audio
      Audio
 Smart Home
   Displays
      Audio
Peripherals
      Audio
Accessories
      Audio
      Audio
Accessories
Peripherals
  Furniture
Accessories
Accessories
      Audio
     Gaming
Peripherals
 Smart Home
      Audio
Accessories
      Audio
Accessories
 Smart Home
Accessories
      Audio
      Audio
Accessories
      Audio
      Audio
Accessories
   Lighting
Accessories
  Furniture
Peripherals
Peripherals
Accessories
Accessories
      Audio
      Audio
      Audio
 Smart Home
      Audio
    Cameras
  Wearables
      Audio
      Audio
      Audio
Accessories
      Audio
Accessories
      Audio
 Smart Home
Accessories
 Smart Home
Accessories
Accessories
  Wearables
   Displays
      Audio
Accessories
 Smart Home
      Audio
Accessories
      Audio
Accessories
Accessories
 Smart Home
 Smart Home
   Lighting
Peripherals
Accessories
Accessories
      Audio
      Audio
Accessories
Accessories
  Wearables
Accessories
 Smart Home
Peripherals
Accessories
      Audio
   Displays
Accessories
Accessories
      Audio
      Audio
Accessories
      Audio
Accessories
 Smart Home
      Audio
      Audio
      Audio
      Audio
      Audio
Accessories
  Furniture
Accessories
      Audio
        NaN
Peripherals
      Audio
Accessories
   Lighting
Accessories
 Smart Home
Accessories
Accessories
      Audio
      Audio
 Smart Home
Accessories
Accessories
 Smart Home
      Audio
Peripherals
   Lighting
   Lighting
Accessories
Peripherals
 Smart Home
   Lighting
Accessories
Accessories
Accessories
 Smart Home
      Audio
Accessories
Accessories
Peripherals
 Smart Home
      Audio
Accessories
 Smart Home
      Audio
  Wearables
Accessories
    Storage
      Audio
Accessories
      Audio
Accessories
 Smart Home
Accessories
Accessories
  Wearables
      Audio
Accessories
Accessories
      Audio
Peripherals
      Audio
   Lighting
Peripherals
Peripherals
   Displays
      Audio
Accessories
      Audio
Accessories
Accessories
      Audio
Accessories
      Audio
      Audio
      Audio
      Audio
   PC Parts
Accessories
Peripherals
Accessories
Peripherals
    Storage
      Audio
  Furniture
 Smart Home
     Gaming
  Wearables
    Storage
      Audio
Peripherals
      Audio
Accessories
      Audio
Accessories
Accessories
Peripherals
      Audio
        NaN
 Smart Home
 Smart Home
      Audio
Accessories
      Audio
        NaN
Accessories
Accessories
Accessories
      Audio
 Smart Home
      Audio
      Audio
Accessories
Accessories
 Smart Home
Accessories
      Audio

In [51]:
# Show all rows with missing category
missing_category = df[df['category'].isna()]
print("Rows with missing category:", len(missing_category))
print("\nColumns to show:")
print(missing_category[['return_id', 'order_id', 'product_id', 'product_name', 'supplier', 'category', 'return_reason']])

Rows with missing category: 60

Columns to show:
      return_id    order_id product_id             product_name  \
166   RET000167  ORD0001586       P025      Screen Cleaning Kit
267   RET000268  ORD0002527       P003      Smart Watch Fitness
311   RET000312  ORD0002931       P004        Smart Plug 4-Pack
399   RET000400  ORD0003799       P005         USB-C Hub 7-in-1
548   RET000549  ORD0005344       P004        Smart Plug 4-Pack
585   RET000586  ORD0005718       P010  Noise Cancel Headphones
682   RET000683  ORD0006676       P014    Docking Station USB-C
739   RET000740  ORD0007295       P005         USB-C Hub 7-in-1
743   RET000744  ORD0007347       P008      Power Bank 20000mAh
744   RET000745  ORD0007347       P004        Smart Plug 4-Pack
883   RET000884  ORD0008547       P024   Phone Stand Adjustable
952   RET000953  ORD0009296       P011  Mechanical Keyboard TKL
1092  RET001093  ORD0010787       P016          27in Monitor 4K
1096  RET001097  ORD0010899       P004        Smart Plug 4-Pack
1102  RET001103  ORD0010913       P012         Gaming Mouse RGB
1165  RET001166  ORD0000077       P002   Bluetooth Speaker Mini
1243  RET001244  ORD0000456       P002   Bluetooth Speaker Mini
1301  RET001302  ORD0000694       P007          Webcam 1080p HD
1302  RET001303  ORD0000698       P004        Smart Plug 4-Pack
1346  RET001347  ORD0000926       P004        Smart Plug 4-Pack
1400  RET001401  ORD0001138       P023     Cable Management Kit
1409  RET001410  ORD0001199       P026            HDMI Cable 2m
1431  RET001432  ORD0001272       P023     Cable Management Kit
1452  RET001453  ORD0001371       P002   Bluetooth Speaker Mini
1558  RET001559  ORD0001796       P002   Bluetooth Speaker Mini
1647  RET001648  ORD0002238       P001     Wireless Earbuds Pro
1653  RET001654  ORD0002278       P002   Bluetooth Speaker Mini
1795  RET001796  ORD0002822       P011  Mechanical Keyboard TKL
1809  RET001810  ORD0002858       P002   Bluetooth Speaker Mini
1862  RET001863  ORD0003096       P002   Bluetooth Speaker Mini
2109  RET002110  ORD0004114       P014    Docking Station USB-C
2122  RET002123  ORD0004149       P001     Wireless Earbuds Pro
2261  RET002262  ORD0004810       P017      Smart LED Desk Lamp
2376  RET002377  ORD0005323       P001     Wireless Earbuds Pro
2377  RET002378  ORD0005327       P004        Smart Plug 4-Pack
2410  RET002411  ORD0005492       P017      Smart LED Desk Lamp
2419  RET002420  ORD0005507       P017      Smart LED Desk Lamp
2433  RET002434  ORD0005559       P004        Smart Plug 4-Pack
2501  RET002502  ORD0005826       P016          27in Monitor 4K
2505  RET002506  ORD0005863       P001     Wireless Earbuds Pro
2690  RET002691  ORD0006617       P005         USB-C Hub 7-in-1
2793  RET002794  ORD0007028       P002   Bluetooth Speaker Mini
2898  RET002899  ORD0007472       P004        Smart Plug 4-Pack
2923  RET002924  ORD0007583       P021    VR Headset Standalone
2934  RET002935  ORD0007632       P001     Wireless Earbuds Pro
2937  RET002938  ORD0007644       P001     Wireless Earbuds Pro
2997  RET002998  ORD0007969       P024   Phone Stand Adjustable
3131  RET003132  ORD0008636       P004        Smart Plug 4-Pack
3180  RET003181  ORD0008851       P022       Laptop Sleeve 15in
3192  RET003193  ORD0008923       P001     Wireless Earbuds Pro
3272  RET003273  ORD0009345       P019          Ring Light 10in
3312  RET003313  ORD0009530       P025      Screen Cleaning Kit
3339  RET003340  ORD0009611       P002   Bluetooth Speaker Mini
3394  RET003395  ORD0009863       P003      Smart Watch Fitness
3424  RET003425  ORD0009960       P016          27in Monitor 4K
3450  RET003451  ORD0010045       P002   Bluetooth Speaker Mini
3574  RET003575  ORD0010543       P006   Laptop Stand Aluminium
3612  RET003613  ORD0010665       P007          Webcam 1080p HD
3718  RET003719  ORD0011137       P027      Cable Clips Pack 50
3784  RET003785  ORD0011425       P002   Bluetooth Speaker Mini

             supplier category          return_reason
166    ValueSource Co      NaN           Changed Mind
267   NovaTech Supply      NaN        Wrong Item Sent
311   NovaTech Supply      NaN        Arrived Damaged
399      TechCore Ltd      NaN  Defective/Not Working
548   NovaTech Supply      NaN  Defective/Not Working
585      TechCore Ltd      NaN           Changed Mind
682   EliteComponents      NaN           Changed Mind
739      TechCore Ltd      NaN       Not as Described
743      TechCore Ltd      NaN       Not as Described
744   NovaTech Supply      NaN  Defective/Not Working
883    ValueSource Co      NaN  Defective/Not Working
952   EliteComponents      NaN        Wrong Item Sent
1092    BrightGadgets      NaN        Wrong Item Sent
1096  NovaTech Supply      NaN  Defective/Not Working
1102  EliteComponents      NaN  Defective/Not Working
1165  NovaTech Supply      NaN  Defective/Not Working
1243  NovaTech Supply      NaN  Defective/Not Working
1301     TechCore Ltd      NaN  Defective/Not Working
1302  NovaTech Supply      NaN  Defective/Not Working
1346  NovaTech Supply      NaN  Defective/Not Working
1400   ValueSource Co      NaN           Changed Mind
1409   ValueSource Co      NaN        Wrong Item Sent
1431   ValueSource Co      NaN       Not as Described
1452  NovaTech Supply      NaN        Arrived Damaged
1558  NovaTech Supply      NaN        Wrong Item Sent
1647  NovaTech Supply      NaN  Defective/Not Working
1653  NovaTech Supply      NaN        Wrong Item Sent
1795  EliteComponents      NaN  Defective/Not Working
1809  NovaTech Supply      NaN  Defective/Not Working
1862  NovaTech Supply      NaN  Defective/Not Working
2109  EliteComponents      NaN  Defective/Not Working
2122  NovaTech Supply      NaN        Wrong Item Sent
2261    BrightGadgets      NaN           Changed Mind
2376  NovaTech Supply      NaN  Defective/Not Working
2377  NovaTech Supply      NaN  Defective/Not Working
2410    BrightGadgets      NaN        Arrived Damaged
2419    BrightGadgets      NaN           Changed Mind
2433  NovaTech Supply      NaN  Defective/Not Working
2501    BrightGadgets      NaN        Wrong Item Sent
2505  NovaTech Supply      NaN        Wrong Item Sent
2690     TechCore Ltd      NaN                    NaN
2793  NovaTech Supply      NaN           Changed Mind
2898  NovaTech Supply      NaN  Defective/Not Working
2923    BrightGadgets      NaN  Defective/Not Working
2934  NovaTech Supply      NaN  Defective/Not Working
2937  NovaTech Supply      NaN  Defective/Not Working
2997   ValueSource Co      NaN  Defective/Not Working
3131  NovaTech Supply      NaN       Not as Described
3180   ValueSource Co      NaN        Wrong Item Sent
3192  NovaTech Supply      NaN        Wrong Item Sent
3272    BrightGadgets      NaN        Wrong Item Sent
3312   ValueSource Co      NaN        Arrived Damaged
3339  NovaTech Supply      NaN  Defective/Not Working
3394  NovaTech Supply      NaN  Defective/Not Working
3424    BrightGadgets      NaN        Wrong Item Sent
3450  NovaTech Supply      NaN  Defective/Not Working
3574     TechCore Ltd      NaN           Changed Mind
3612     TechCore Ltd      NaN       Not as Described
3718   ValueSource Co      NaN  Defective/Not Working
3784  NovaTech Supply      NaN       Not as Described

In [53]:
# Create product_id -> category mapping from rows where category exists
product_category_map = df[df['category'].notna()][['product_id', 'category']].drop_duplicates()
product_category_map = product_category_map.set_index('product_id')['category'].to_dict()

print("Product to Category mapping:")
for pid, cat in sorted(product_category_map.items()):
    print(f"  {pid}: {cat}")

# Fill missing category using the mapping
df['category'] = df.apply(
    lambda row: product_category_map[row['product_id']] if pd.isna(row['category']) else row['category'],
    axis=1
)

# Verify
print("\ncategory nulls after fill:", df['category'].isna().sum())
print("\nCategory value counts:")
print(df['category'].value_counts())

Product to Category mapping:
  P001: Audio
  P002: Audio
  P003: Wearables
  P004: Smart Home
  P005: Accessories
  P006: Accessories
  P007: Peripherals
  P008: Accessories
  P009: Accessories
  P010: Audio
  P011: Peripherals
  P012: Peripherals
  P013: Storage
  P014: Accessories
  P015: Audio
  P016: Displays
  P017: Lighting
  P018: Cameras
  P019: Lighting
  P020: Accessories
  P021: Gaming
  P022: Accessories
  P023: Accessories
  P024: Accessories
  P025: Accessories
  P026: Accessories
  P027: Accessories
  P028: Furniture
  P029: PC Parts
  P030: Peripherals

category nulls after fill: 0

Category value counts:
category
Accessories    1205
Audio          1181
Peripherals     435
Smart Home      301
Wearables       164
Lighting        141
Displays        110
Storage          78
Furniture        57
Cameras          49
Gaming           39
PC Parts         31
Name: count, dtype: int64

In [55]:
# Check return_date
print("return_date nulls:", df['return_date'].isna().sum())
print("First 5 return_date values:")
print(df['return_date'].head())

# Convert to datetime
df['return_date'] = pd.to_datetime(df['return_date'], errors='coerce')

# Check how many failed to parse
print("\nFailed to parse:", df['return_date'].isna().sum())

# Show date range
print("Date range:", df['return_date'].min(), "to", df['return_date'].max())

# Show distribution by year
print("\nReturns by year:")
print(df['return_date'].dt.year.value_counts().sort_index())

return_date nulls: 0
First 5 return_date values:
0   2024-06-07
1   2023-08-09
2   2024-03-17
3   2024-03-06
4   2022-12-16
Name: return_date, dtype: datetime64[us]

Failed to parse: 0
Date range: 2021-01-10 00:00:00 to 2025-01-24 00:00:00

Returns by year:
return_date
2021       5
2022     640
2023    1246
2024    1807
2025      93
Name: count, dtype: int64

In [57]:
# Check return_reason
print("return_reason nulls:", df['return_reason'].isna().sum())
print("return_reason unique:", df['return_reason'].nunique())
print("First 10 return_reason values:")
print(df['return_reason'].head(10))

# Show value counts (excluding NaN)
print("\nReturn reason value counts:")
print(df['return_reason'].value_counts(dropna=True))

return_reason nulls: 121
return_reason unique: 6
First 10 return_reason values:
0    Defective/Not Working
1    Defective/Not Working
2             Changed Mind
3          Wrong Item Sent
4          Wrong Item Sent
5    Defective/Not Working
6    Defective/Not Working
7          Arrived Damaged
8    Defective/Not Working
9          Wrong Item Sent
Name: return_reason, dtype: str

Return reason value counts:
return_reason
Defective/Not Working    1711
Not as Described          614
Changed Mind              409
Arrived Damaged           387
Wrong Item Sent           331
Poor Quality              218
Name: count, dtype: int64

In [61]:
# Show all rows with missing return_reason
missing_reason = df[df['return_reason'].isna()]
print("Rows with missing return_reason:", len(missing_reason))
print("\nColumns to show:")
print(missing_reason[['return_id', 'order_id', 'product_id', 'product_name', 'supplier', 'category', 'return_reason', 'refund_amount']])

Rows with missing return_reason: 0

Columns to show:
Empty DataFrame
Columns: [return_id, order_id, product_id, product_name, supplier, category, return_reason, refund_amount]
Index: []

In [60]:
# Create product_id -> most common return_reason mapping
product_reason_map = df[df['return_reason'].notna()].groupby('product_id')['return_reason'].agg(
    lambda x: x.value_counts().index[0]
).to_dict()

print("Product to most common return reason mapping:")
for pid, reason in sorted(product_reason_map.items()):
    print(f"  {pid}: {reason}")

# Fill missing return_reason using the mapping
df['return_reason'] = df.apply(
    lambda row: product_reason_map[row['product_id']] if pd.isna(row['return_reason']) else row['return_reason'],
    axis=1
)

# Verify
print("\nreturn_reason nulls after fill:", df['return_reason'].isna().sum())
print("\nReturn reason value counts:")
print(df['return_reason'].value_counts())

Product to most common return reason mapping:
  P001: Defective/Not Working
  P002: Defective/Not Working
  P003: Defective/Not Working
  P004: Defective/Not Working
  P005: Defective/Not Working
  P006: Defective/Not Working
  P007: Defective/Not Working
  P008: Defective/Not Working
  P009: Defective/Not Working
  P010: Defective/Not Working
  P011: Defective/Not Working
  P012: Defective/Not Working
  P013: Defective/Not Working
  P014: Defective/Not Working
  P015: Defective/Not Working
  P016: Defective/Not Working
  P017: Defective/Not Working
  P018: Defective/Not Working
  P019: Defective/Not Working
  P020: Defective/Not Working
  P021: Defective/Not Working
  P022: Defective/Not Working
  P023: Defective/Not Working
  P024: Defective/Not Working
  P025: Defective/Not Working
  P026: Defective/Not Working
  P027: Defective/Not Working
  P028: Defective/Not Working
  P029: Defective/Not Working
  P030: Defective/Not Working

return_reason nulls after fill: 0

Return reason value counts:
return_reason
Defective/Not Working    1832
Not as Described          614
Changed Mind              409
Arrived Damaged           387
Wrong Item Sent           331
Poor Quality              218
Name: count, dtype: int64

In [62]:
# Check refund_amount
print("refund_amount nulls:", df['refund_amount'].isna().sum())
print("refund_amount describe:")
print(df['refund_amount'].describe())

# Check for negative or zero values
print("\nNegative refunds:", (df['refund_amount'] < 0).sum())
print("Zero refunds:", (df['refund_amount'] == 0).sum())

# Check for outliers using IQR
Q1 = df['refund_amount'].quantile(0.25)
Q3 = df['refund_amount'].quantile(0.75)
IQR = Q3 - Q1
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
outliers = df[(df['refund_amount'] < lower) | (df['refund_amount'] > upper)]
print("\nOutliers (IQR method):", outliers.shape[0])
print("Outlier values:")
print(outliers[['product_id', 'product_name', 'refund_amount', 'qty_returned']].head(10))

# Show max refund amounts
print("\nTop 10 highest refund amounts:")
print(df.nlargest(10, 'refund_amount')[['product_id', 'product_name', 'refund_amount', 'qty_returned']])

refund_amount nulls: 0
refund_amount describe:
count    3791.000000
mean       75.773893
std       104.253584
min      -130.490000
25%        30.370000
50%        46.270000
75%        86.150000
max      1694.840000
Name: refund_amount, dtype: float64

Negative refunds: 5
Zero refunds: 0

Outliers (IQR method): 322
Outlier values:
   product_id             product_name  refund_amount  qty_returned
3        P011  Mechanical Keyboard TKL         174.35             2
6        P006   Laptop Stand Aluminium        1414.36             1
13       P016          27in Monitor 4K         950.58             3
17       P016          27in Monitor 4K         318.63             1
31       P016          27in Monitor 4K         306.60             1
35       P003      Smart Watch Fitness         406.75             3
36       P016          27in Monitor 4K         248.85             1
45       P003      Smart Watch Fitness         232.99             2
47       P028   Gaming Chair Ergonomic         349.05             1
51       P013         Portable SSD 1TB         240.94             3

Top 10 highest refund amounts:
     product_id            product_name  refund_amount  qty_returned
1539       P001    Wireless Earbuds Pro        1694.84             1
3572       P016         27in Monitor 4K        1467.52             1
6          P006  Laptop Stand Aluminium        1414.36             1
3350       P003     Smart Watch Fitness        1150.48             3
2124       P028  Gaming Chair Ergonomic        1006.47             3
2119       P028  Gaming Chair Ergonomic         966.10             3
13         P016         27in Monitor 4K         950.58             3
2370       P016         27in Monitor 4K         942.43             3
2202       P028  Gaming Chair Ergonomic         942.05             3
961        P016         27in Monitor 4K         937.76             3

In [63]:
# Show negative refund rows
print("Negative refund rows:")
print(df[df['refund_amount'] < 0][['return_id', 'product_id', 'product_name', 'refund_amount', 'qty_returned', 'return_reason']])

# Check if high refunds match high-priced products
print("\nCheck refund per unit (refund_amount / qty_returned):")
df['refund_per_unit'] = df['refund_amount'] / df['qty_returned']
print(df.nlargest(10, 'refund_per_unit')[['product_id', 'product_name', 'refund_amount', 'qty_returned', 'refund_per_unit']])

Negative refund rows:
      return_id product_id            product_name  refund_amount  \
1314  RET001315       P001    Wireless Earbuds Pro         -99.38
1410  RET001411       P027     Cable Clips Pack 50          -4.43
2271  RET002272       P017     Smart LED Desk Lamp         -41.21
2328  RET002329       P001    Wireless Earbuds Pro        -130.49
2828  RET002829       P002  Bluetooth Speaker Mini         -54.82

      qty_returned          return_reason
1314             2        Wrong Item Sent
1410             1  Defective/Not Working
2271             1  Defective/Not Working
2328             3  Defective/Not Working
2828             1  Defective/Not Working

Check refund per unit (refund_amount / qty_returned):
     product_id            product_name  refund_amount  qty_returned  \
1539       P001    Wireless Earbuds Pro        1694.84             1
3572       P016         27in Monitor 4K        1467.52             1
6          P006  Laptop Stand Aluminium        1414.36             1
3350       P003     Smart Watch Fitness        1150.48             3
47         P028  Gaming Chair Ergonomic         349.05             1
1633       P028  Gaming Chair Ergonomic         694.82             2
2116       P028  Gaming Chair Ergonomic         347.10             1
283        P028  Gaming Chair Ergonomic         691.39             2
1469       P028  Gaming Chair Ergonomic         345.59             1
732        P028  Gaming Chair Ergonomic         344.89             1

      refund_per_unit
1539      1694.840000
3572      1467.520000
6         1414.360000
3350       383.493333
47         349.050000
1633       347.410000
2116       347.100000
283        345.695000
1469       345.590000
732        344.890000

In [64]:
# Fix negative refunds (make absolute value)
df.loc[df['refund_amount'] < 0, 'refund_amount'] = df.loc[df['refund_amount'] < 0, 'refund_amount'].abs()

# Verify no more negative refunds
print("Negative refunds after fix:", (df['refund_amount'] < 0).sum())

# Check refund_per_unit for potential data errors
df['refund_per_unit'] = df['refund_amount'] / df['qty_returned']

# Flag suspicious high refund_per_unit (e.g., > 500 for most products)
print("\nSuspicious high refund_per_unit (>500):")
suspicious = df[df['refund_per_unit'] > 500][['return_id', 'product_id', 'product_name', 'refund_amount', 'qty_returned', 'refund_per_unit']]
print(suspicious)

# Optional: Flag these rows (add a column)
df['suspicious_refund'] = df['refund_per_unit'] > 500
print("\nSuspicious refund count:", df['suspicious_refund'].sum())

Negative refunds after fix: 0

Suspicious high refund_per_unit (>500):
      return_id product_id            product_name  refund_amount  \
6     RET000007       P006  Laptop Stand Aluminium        1414.36
1539  RET001540       P001    Wireless Earbuds Pro        1694.84
3572  RET003573       P016         27in Monitor 4K        1467.52

      qty_returned  refund_per_unit
6                1          1414.36
1539             1          1694.84
3572             1          1467.52

Suspicious refund count: 3

In [66]:
# Check qty_returned
print("qty_returned nulls:", df['qty_returned'].isna().sum())
print("qty_returned describe:")
print(df['qty_returned'].describe())

# Check for negative or zero values
print("\nNegative qty:", (df['qty_returned'] < 0).sum())
print("Zero qty:", (df['qty_returned'] == 0).sum())

# Show unique values
print("\nUnique qty values:")
print(df['qty_returned'].value_counts().sort_index())

# Check max quantities
print("\nTop 10 highest qty_returned:")
print(df.nlargest(10, 'qty_returned')[['return_id', 'product_id', 'product_name', 'qty_returned', 'refund_amount']])

qty_returned nulls: 0
qty_returned describe:
count    3791.000000
mean        1.540491
std        16.213773
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max       999.000000
Name: qty_returned, dtype: float64

Negative qty: 0
Zero qty: 0

Unique qty values:
qty_returned
1      2935
2       659
3       196
999       1
Name: count, dtype: int64

Top 10 highest qty_returned:
     return_id product_id             product_name  qty_returned  \
646  RET000647       P023     Cable Management Kit           999
13   RET000014       P016          27in Monitor 4K             3
23   RET000024       P005         USB-C Hub 7-in-1             3
35   RET000036       P003      Smart Watch Fitness             3
43   RET000044       P007          Webcam 1080p HD             3
51   RET000052       P013         Portable SSD 1TB             3
74   RET000075       P006   Laptop Stand Aluminium             3
127  RET000128       P010  Noise Cancel Headphones             3
133  RET000134       P030            Webcam 4K Pro             3
136  RET000137       P014    Docking Station USB-C             3

     refund_amount
646          23.75
13          950.58
23           98.79
35          406.75
43          161.60
51          240.94
74           90.96
127          89.20
133         411.95
136         300.65

In [68]:
# Fix the 999 qty error (likely a typo — set to 1 or investigate)
print("Row with qty=999:")
print(df[df['qty_returned'] == 999][['return_id', 'product_id', 'product_name', 'qty_returned', 'refund_amount']])

# Fix: set 999 to 1 (most likely intended value)
df.loc[df['qty_returned'] == 999, 'qty_returned'] = 1

# Verify
print("\nqty_returned describe after fix:")
print(df['qty_returned'].describe())
print("\nUnique qty values after fix:")
print(df['qty_returned'].value_counts().sort_index())

Row with qty=999:
Empty DataFrame
Columns: [return_id, product_id, product_name, qty_returned, refund_amount]
Index: []

qty_returned describe after fix:
count    3791.000000
mean        1.277236
std         0.551234
min         1.000000
25%         1.000000
50%         1.000000
75%         1.000000
max         3.000000
Name: qty_returned, dtype: float64

Unique qty values after fix:
qty_returned
1    2936
2     659
3     196
Name: count, dtype: int64

In [70]:
# # Save cleaned data
# df.to_csv("returns_data_cleaned.csv", index=False)
# print("Cleaned dataset saved to returns_data_cleaned.csv")

# Final summary
print("\n" + "="*50)
print("CLEANING COMPLETE")
print("="*50)
print(f"Total rows: {len(df)}")
print(f"Total columns: {len(df.columns)}")
print("\nColumns cleaned:")
print("  1. return_id - OK (no changes needed)")
print("  2. order_id - OK (no changes needed)")
print("  3. item_id - OK (duplicates expected)")
print("  4. product_id - OK (no changes needed)")
print("  5. product_name - OK (stripped whitespace)")
print("  6. supplier - Standardized 24 → 5 unique values")
print("  7. category - Filled 60 missing using product_id mapping")
print("  8. return_date - Converted to datetime (no errors)")
print("  9. return_reason - Filled 121 missing using product_id mapping")
print(" 10. refund_amount - Fixed 5 negative values, flagged 3 suspicious")
print(" 11. qty_returned - Fixed 1 error (999 → 1)")
print("\nNew columns added:")
print("  - refund_per_unit")
print("  - suspicious_refund (boolean)")

==================================================
CLEANING COMPLETE
==================================================
Total rows: 3791
Total columns: 13

Columns cleaned:
  1. return_id - OK (no changes needed)
  2. order_id - OK (no changes needed)
  3. item_id - OK (duplicates expected)
  4. product_id - OK (no changes needed)
  5. product_name - OK (stripped whitespace)
  6. supplier - Standardized 24 → 5 unique values
  7. category - Filled 60 missing using product_id mapping
  8. return_date - Converted to datetime (no errors)
  9. return_reason - Filled 121 missing using product_id mapping
 10. refund_amount - Fixed 5 negative values, flagged 3 suspicious
 11. qty_returned - Fixed 1 error (999 → 1)

New columns added:
  - refund_per_unit
  - suspicious_refund (boolean)

In [72]:
# View the cleaned dataset
print("First 10 rows:")
df.head(10)

# Check the structure
print("\nDataset info:")
df.info()

# Quick summary
print("\nFirst 15 rows with all columns:")
df.head(15)

First 10 rows:

Dataset info:
<class 'pandas.DataFrame'>
RangeIndex: 3791 entries, 0 to 3790
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   return_id          3791 non-null   str
 1   order_id           3791 non-null   str
 2   item_id            3791 non-null   str
 3   product_id         3791 non-null   str
 4   product_name       3791 non-null   str
 5   supplier           3791 non-null   str
 6   category           3791 non-null   str
 7   return_date        3791 non-null   datetime64[us]
 8   return_reason      3791 non-null   str
 9   refund_amount      3791 non-null   float64
 10  qty_returned       3791 non-null   int64
 11  refund_per_unit    3791 non-null   float64
 12  suspicious_refund  3791 non-null   bool
dtypes: bool(1), datetime64[us](1), float64(2), int64(1), str(8)
memory usage: 359.2 KB

First 15 rows with all columns:

,return_id,order_id,item_id,product_id,product_name,supplier,category,return_date,return_reason,refund_amount,qty_returned,refund_per_unit,suspicious_refund
0,RET000001,ORD0000013,ITM0000020,P008,Power Bank 20000mAh,TechCore Ltd,Accessories,2024-06-07,Defective/Not Working,9.96,1,9.960,False
1,RET000002,ORD0000020,ITM0000031,P007,Webcam 1080p HD,TechCore Ltd,Peripherals,2023-08-09,Defective/Not Working,50.29,1,50.290,False
2,RET000003,ORD0000045,ITM0000068,P019,Ring Light 10in,BrightGadgets,Lighting,2024-03-17,Changed Mind,54.96,1,54.960,False
3,RET000004,ORD0000045,ITM0000069,P011,Mechanical Keyboard TKL,EliteComponents,Peripherals,2024-03-06,Wrong Item Sent,174.35,2,87.175,False
4,RET000005,ORD0000057,ITM0000089,P024,Phone Stand Adjustable,ValueSource Co,Accessories,2022-12-16,Wrong Item Sent,7.97,1,7.970,False
5,RET000006,ORD0000057,ITM0000090,P015,Microphone USB Condenser,EliteComponents,Audio,2022-12-23,Defective/Not Working,86.55,1,86.550,False
6,RET000007,ORD0000068,ITM0000109,P006,Laptop Stand Aluminium,TechCore Ltd,Accessories,2023-01-06,Defective/Not Working,1414.36,1,1414.360,True
7,RET000008,ORD0000068,ITM0000110,P006,Laptop Stand Aluminium,TechCore Ltd,Accessories,2022-12-26,Arrived Damaged,39.03,1,39.030,False
8,RET000009,ORD0000076,ITM0000121,P003,Smart Watch Fitness,NovaTech Supply,Wearables,2023-06-22,Defective/Not Working,138.50,1,138.500,False
9,RET000010,ORD0000090,ITM0000142,P011,Mechanical Keyboard TKL,EliteComponents,Peripherals,2023-10-02,Wrong Item Sent,80.99,1,80.990,False
10,RET000011,ORD0000109,ITM0000175,P009,Desk Pad XL,TechCore Ltd,Accessories,2022-10-28,Poor Quality,24.11,1,24.110,False
11,RET000012,ORD0000110,ITM0000176,P012,Gaming Mouse RGB,EliteComponents,Peripherals,2022-12-08,Changed Mind,42.85,1,42.850,False
12,RET000013,ORD0000128,ITM0000207,P029,Thermal Paste Premium,EliteComponents,PC Parts,2024-11-24,Defective/Not Working,9.61,1,9.610,False
13,RET000014,ORD0000128,ITM0000208,P016,27in Monitor 4K,BrightGadgets,Displays,2024-12-10,Changed Mind,950.58,3,316.860,False
14,RET000015,ORD0000128,ITM0000209,P025,Screen Cleaning Kit,ValueSource Co,Accessories,2024-12-12,Defective/Not Working,7.17,1,7.170,False

In [73]:
# Export to CSV
df.to_csv("returns_data_cleaned.csv", index=False)
print("Exported to returns_data_cleaned.csv")

# Verify in pandas
df_exported = pd.read_csv("returns_data_cleaned.csv")
df_exported.head(10)

Exported to returns_data_cleaned.csv

,return_id,order_id,item_id,product_id,product_name,supplier,category,return_date,return_reason,refund_amount,qty_returned,refund_per_unit,suspicious_refund
0,RET000001,ORD0000013,ITM0000020,P008,Power Bank 20000mAh,TechCore Ltd,Accessories,2024-06-07,Defective/Not Working,9.96,1,9.960,False
1,RET000002,ORD0000020,ITM0000031,P007,Webcam 1080p HD,TechCore Ltd,Peripherals,2023-08-09,Defective/Not Working,50.29,1,50.290,False
2,RET000003,ORD0000045,ITM0000068,P019,Ring Light 10in,BrightGadgets,Lighting,2024-03-17,Changed Mind,54.96,1,54.960,False
3,RET000004,ORD0000045,ITM0000069,P011,Mechanical Keyboard TKL,EliteComponents,Peripherals,2024-03-06,Wrong Item Sent,174.35,2,87.175,False
4,RET000005,ORD0000057,ITM0000089,P024,Phone Stand Adjustable,ValueSource Co,Accessories,2022-12-16,Wrong Item Sent,7.97,1,7.970,False
5,RET000006,ORD0000057,ITM0000090,P015,Microphone USB Condenser,EliteComponents,Audio,2022-12-23,Defective/Not Working,86.55,1,86.550,False
6,RET000007,ORD0000068,ITM0000109,P006,Laptop Stand Aluminium,TechCore Ltd,Accessories,2023-01-06,Defective/Not Working,1414.36,1,1414.360,True
7,RET000008,ORD0000068,ITM0000110,P006,Laptop Stand Aluminium,TechCore Ltd,Accessories,2022-12-26,Arrived Damaged,39.03,1,39.030,False
8,RET000009,ORD0000076,ITM0000121,P003,Smart Watch Fitness,NovaTech Supply,Wearables,2023-06-22,Defective/Not Working,138.50,1,138.500,False
9,RET000010,ORD0000090,ITM0000142,P011,Mechanical Keyboard TKL,EliteComponents,Peripherals,2023-10-02,Wrong Item Sent,80.99,1,80.990,False