In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('inventory.csv')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 32880 entries, 0 to 32879
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   product_id     32880 non-null  str
 1   date           32880 non-null  str
 2   stock_level    32880 non-null  int64
 3   units_sold     32880 non-null  int64
 4   stockout_flag  32880 non-null  int64
dtypes: int64(3), str(2)
memory usage: 1.3 MB

In [8]:
df.head(30)

   product_id        date  stock_level  units_sold  stockout_flag
0        P001  2022-01-01          554           6              0
1        P001  2022-01-02          545           9              0
2        P001  2022-01-03          541           4              0
3        P001  2022-01-04          536           5              0
4        P001  2022-01-05          531           5              0
5        P001  2022-01-06          526           5              0
6        P001  2022-01-07          521           5              0
7        P001  2022-01-08          516           5              0
8        P001  2022-01-09          509           7              0
9        P001  2022-01-10          505           4              0
10       P001  2022-01-11          501           4              0
11       P001  2022-01-12          496           5              0
12       P001  2022-01-13          489           7              0
13       P001  2022-01-14          485           4              0
14       P001  2022-01-15          478           7              0
15       P001  2022-01-16          472           6              0
16       P001  2022-01-17          467           5              0
17       P001  2022-01-18          461           6              0
18       P001  2022-01-19          456           5              0
19       P001  2022-01-20          451           5              0
20       P001  2022-01-21          446           5              0
21       P001  2022-01-22          435          11              0
22       P001  2022-01-23          424          11              0
23       P001  2022-01-24          420           4              0
24       P001  2022-01-25          416           4              0
25       P001  2022-01-26          409           7              0
26       P001  2022-01-27          406           3              0
27       P001  2022-01-28          401           5              0
28       P001  2022-01-29          393           8              0
29       P001  2022-01-30          388           5              0

In [10]:
# 1) Basic check
df["product_id"].head()

# 2) Data type
df["product_id"].dtype

# 3) Missing values
df["product_id"].isna().sum()

# 4) Unique values
df["product_id"].nunique()

# 5) Sample values
df["product_id"].value_counts().head(10)

product_id
P001    1096
P002    1096
P003    1096
P004    1096
P005    1096
P006    1096
P007    1096
P008    1096
P009    1096
P010    1096
Name: count, dtype: int64

In [13]:
df["product_id"] = df["product_id"].astype(str).str.strip()
df["product_id"].nunique()
df["product_id"].value_counts()

product_id
P001    1096
P002    1096
P003    1096
P004    1096
P005    1096
P006    1096
P007    1096
P008    1096
P009    1096
P010    1096
P011    1096
P012    1096
P013    1096
P014    1096
P015    1096
P016    1096
P017    1096
P018    1096
P019    1096
P020    1096
P021    1096
P022    1096
P023    1096
P024    1096
P025    1096
P026    1096
P027    1096
P028    1096
P029    1096
P030    1096
Name: count, dtype: int64

In [12]:
df["product_id"] = df["product_id"].astype(str).str.strip()

df["product_id"].nunique()
df["product_id"].value_counts()
df["product_id"].str.match(r"^P\d{3}$").all()

np.True_

In [14]:
df["product_id"].str.match(r"^P\d{3}$").value_counts()

product_id
True    32880
Name: count, dtype: int64

In [15]:
df["product_id"] = df["product_id"].astype(str).str.strip()
df["product_id"].str.match(r"^P\d{3}$").all()

np.True_

In [16]:
df["date"].head()
df["date"].dtype
df["date"].isna().sum()

np.int64(0)

In [18]:
df["product_id"] = df["product_id"].astype(str).str.strip()
df["product_id"].nunique()
df["product_id"].value_counts()
df["product_id"].str.match(r"^P\d{3}$").all()

np.True_

In [19]:
df["date"] = pd.to_datetime(df["date"], errors="coerce")
df["date"].isna().sum()
df["date"].min(), df["date"].max()
df["date"].dtype

dtype('<M8[us]')

In [23]:
df["date"].min(), df["date"].max()
df["date"].isna().sum()
df["date"].dt.year.value_counts().sort_index()

date
2022    10950
2023    10950
2024    10980
Name: count, dtype: int64

In [27]:
df["date"].min(), df["date"].max()
df["date"].dt.month.value_counts().sort_index()
df["date"].dt.day_name().value_counts()

date
Saturday     4710
Sunday       4710
Monday       4710
Tuesday      4710
Wednesday    4680
Thursday     4680
Friday       4680
Name: count, dtype: int64

In [29]:
df["weekday"] = df["date"].dt.day_name()
df["month"] = df["date"].dt.month_name()
df["year"] = df["date"].dt.year
df["day"] = df["date"].dt.day

In [31]:
df["weekday"].value_counts().head()
df["month"].value_counts().head()
df["year"].value_counts()
df["day"].head()

0    1
1    2
2    3
3    4
4    5
Name: day, dtype: int32

In [32]:
df["stock_level"].head()
df["stock_level"].dtype
df["stock_level"].isna().sum()
df["stock_level"].describe()
df["stock_level"].min(), df["stock_level"].max()

(np.int64(0), np.int64(809))

In [33]:
df["stock_level"].min()
df["stock_level"].max()
df["stock_level"].describe()
(df["stock_level"] < 0).sum()

np.int64(0)

In [35]:
df["units_sold"].head()
df["units_sold"].dtype
df["units_sold"].isna().sum()
df["units_sold"].describe()
(df["units_sold"] < 0).sum()

np.int64(0)

In [40]:
df["units_sold"].head()
df["units_sold"].dtype
df["units_sold"].isna().sum()
df["units_sold"].describe()
(df["units_sold"] < 0).sum()

np.int64(0)

In [42]:
df["stockout_flag"].head()
df["stockout_flag"].dtype
df["stockout_flag"].isna().sum()
df["stockout_flag"].value_counts()
df["stockout_flag"].unique()

array([0, 1])

In [47]:
df["stockout_flag"].isin([0, 1]).all()
df["stockout_flag"].isin([0, 1]).all()

np.True_

In [49]:
df.groupby("product_id")[["stock_level", "units_sold", "stockout_flag"]].mean()

            stock_level  units_sold  stockout_flag
product_id
P001         288.949818    8.417883       0.151460
P002         283.232664    8.417883       0.151460
P003         280.596715    8.417883       0.164234
P004         197.048358    5.411496       0.138686
P005         287.346715    8.417883       0.156934
P006         276.814781    8.417883       0.165146
P007         293.714416    8.417883       0.154197
P008         268.642336    8.417883       0.155109
P009         199.774635    5.411496       0.141423
P010         194.307482    5.411496       0.147810
P011         281.166971    8.417883       0.157847
P012         262.074818    8.417883       0.167883
P013         203.552007    5.411496       0.141423
P014         202.011861    5.411496       0.146898
P015         142.007299    3.006387       0.102190
P016         204.228102    5.411496       0.137774
P017         137.006387    3.006387       0.112226
P018         140.159672    3.006387       0.094891
P019         140.577555    3.006387       0.102190
P020         134.453467    3.006387       0.108577
P021         105.211679    1.651460       0.054745
P022         138.623175    3.006387       0.103102
P023         144.523723    3.006387       0.097628
P024         213.858577    5.411496       0.136861
P025         207.192518    5.411496       0.136861
P026         204.317518    5.411496       0.133212
P027         140.252737    3.006387       0.099453
P028         110.634124    1.651460       0.041971
P029         109.271898    1.651460       0.041971
P030         142.327555    3.006387       0.103102

In [51]:
product_summary = df.groupby("product_id").agg(
    avg_stock_level=("stock_level", "mean"),
    avg_units_sold=("units_sold", "mean"),
    stockout_rate=("stockout_flag", "mean")
).reset_index()

In [53]:
product_summary.sort_values("stockout_rate", ascending=False)

   product_id  avg_stock_level  avg_units_sold  stockout_rate
11       P012       262.074818        8.417883       0.167883
5        P006       276.814781        8.417883       0.165146
2        P003       280.596715        8.417883       0.164234
10       P011       281.166971        8.417883       0.157847
4        P005       287.346715        8.417883       0.156934
7        P008       268.642336        8.417883       0.155109
6        P007       293.714416        8.417883       0.154197
0        P001       288.949818        8.417883       0.151460
1        P002       283.232664        8.417883       0.151460
9        P010       194.307482        5.411496       0.147810
13       P014       202.011861        5.411496       0.146898
8        P009       199.774635        5.411496       0.141423
12       P013       203.552007        5.411496       0.141423
3        P004       197.048358        5.411496       0.138686
15       P016       204.228102        5.411496       0.137774
23       P024       213.858577        5.411496       0.136861
24       P025       207.192518        5.411496       0.136861
25       P026       204.317518        5.411496       0.133212
16       P017       137.006387        3.006387       0.112226
19       P020       134.453467        3.006387       0.108577
29       P030       142.327555        3.006387       0.103102
21       P022       138.623175        3.006387       0.103102
14       P015       142.007299        3.006387       0.102190
18       P019       140.577555        3.006387       0.102190
26       P027       140.252737        3.006387       0.099453
22       P023       144.523723        3.006387       0.097628
17       P018       140.159672        3.006387       0.094891
20       P021       105.211679        1.651460       0.054745
27       P028       110.634124        1.651460       0.041971
28       P029       109.271898        1.651460       0.041971

In [55]:
product_summary.sort_values("stockout_rate").head(5)
product_summary.sort_values("stockout_rate", ascending=False).head(5)

   product_id  avg_stock_level  avg_units_sold  stockout_rate
11       P012       262.074818        8.417883       0.167883
5        P006       276.814781        8.417883       0.165146
2        P003       280.596715        8.417883       0.164234
10       P011       281.166971        8.417883       0.157847
4        P005       287.346715        8.417883       0.156934

In [57]:
df.head(50)

,product_id,date,stock_level,units_sold,stockout_flag,weekday,month,year,day
0,P001,2022-01-01,554,6,0,Saturday,January,2022,1
1,P001,2022-01-02,545,9,0,Sunday,January,2022,2
2,P001,2022-01-03,541,4,0,Monday,January,2022,3
3,P001,2022-01-04,536,5,0,Tuesday,January,2022,4
4,P001,2022-01-05,531,5,0,Wednesday,January,2022,5
5,P001,2022-01-06,526,5,0,Thursday,January,2022,6
6,P001,2022-01-07,521,5,0,Friday,January,2022,7
7,P001,2022-01-08,516,5,0,Saturday,January,2022,8
8,P001,2022-01-09,509,7,0,Sunday,January,2022,9
9,P001,2022-01-10,505,4,0,Monday,January,2022,10
10,P001,2022-01-11,501,4,0,Tuesday,January,2022,11
11,P001,2022-01-12,496,5,0,Wednesday,January,2022,12
12,P001,2022-01-13,489,7,0,Thursday,January,2022,13
13,P001,2022-01-14,485,4,0,Friday,January,2022,14
14,P001,2022-01-15,478,7,0,Saturday,January,2022,15
15,P001,2022-01-16,472,6,0,Sunday,January,2022,16
16,P001,2022-01-17,467,5,0,Monday,January,2022,17
17,P001,2022-01-18,461,6,0,Tuesday,January,2022,18
18,P001,2022-01-19,456,5,0,Wednesday,January,2022,19
19,P001,2022-01-20,451,5,0,Thursday,January,2022,20
20,P001,2022-01-21,446,5,0,Friday,January,2022,21
21,P001,2022-01-22,435,11,0,Saturday,January,2022,22
22,P001,2022-01-23,424,11,0,Sunday,January,2022,23
23,P001,2022-01-24,420,4,0,Monday,January,2022,24
24,P001,2022-01-25,416,4,0,Tuesday,January,2022,25
25,P001,2022-01-26,409,7,0,Wednesday,January,2022,26
26,P001,2022-01-27,406,3,0,Thursday,January,2022,27
27,P001,2022-01-28,401,5,0,Friday,January,2022,28
28,P001,2022-01-29,393,8,0,Saturday,January,2022,29
29,P001,2022-01-30,388,5,0,Sunday,January,2022,30
30,P001,2022-01-31,381,7,0,Monday,January,2022,31
31,P001,2022-02-01,653,8,0,Tuesday,February,2022,1
32,P001,2022-02-02,648,5,0,Wednesday,February,2022,2
33,P001,2022-02-03,641,7,0,Thursday,February,2022,3
34,P001,2022-02-04,637,4,0,Friday,February,2022,4
35,P001,2022-02-05,628,9,0,Saturday,February,2022,5
36,P001,2022-02-06,622,6,0,Sunday,February,2022,6
37,P001,2022-02-07,614,8,0,Monday,February,2022,7
38,P001,2022-02-08,608,6,0,Tuesday,February,2022,8
39,P001,2022-02-09,603,5,0,Wednesday,February,2022,9
40,P001,2022-02-10,596,7,0,Thursday,February,2022,10
41,P001,2022-02-11,588,8,0,Friday,February,2022,11
42,P001,2022-02-12,576,12,0,Saturday,February,2022,12
43,P001,2022-02-13,566,10,0,Sunday,February,2022,13
44,P001,2022-02-14,561,5,0,Monday,February,2022,14
45,P001,2022-02-15,553,8,0,Tuesday,February,2022,15
46,P001,2022-02-16,545,8,0,Wednesday,February,2022,16
47,P001,2022-02-17,540,5,0,Thursday,February,2022,17
48,P001,2022-02-18,535,5,0,Friday,February,2022,18
49,P001,2022-02-19,522,13,0,Saturday,February,2022,19

In [58]:
# Export to CSV
df.to_csv("cleaned_inventory.csv", index=False)
print("Exported to cleaned_inventory.csv")

# Verify in pandas
df_exported = pd.read_csv("cleaned_inventory.csv")
df_exported.head(10)

Exported to cleaned_inventory.csv

,product_id,date,stock_level,units_sold,stockout_flag,weekday,month,year,day
0,P001,2022-01-01,554,6,0,Saturday,January,2022,1
1,P001,2022-01-02,545,9,0,Sunday,January,2022,2
2,P001,2022-01-03,541,4,0,Monday,January,2022,3
3,P001,2022-01-04,536,5,0,Tuesday,January,2022,4
4,P001,2022-01-05,531,5,0,Wednesday,January,2022,5
5,P001,2022-01-06,526,5,0,Thursday,January,2022,6
6,P001,2022-01-07,521,5,0,Friday,January,2022,7
7,P001,2022-01-08,516,5,0,Saturday,January,2022,8
8,P001,2022-01-09,509,7,0,Sunday,January,2022,9
9,P001,2022-01-10,505,4,0,Monday,January,2022,10