In [3]:
import pandas as pd
import numpy as np

In [49]:
df = pd.read_csv('products.csv')

In [50]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    30 non-null     str
 1   product_name  30 non-null     str
 2   category      30 non-null     str
 3   supplier      30 non-null     str
 4   cost_price    30 non-null     float64
 5   sell_price    30 non-null     float64
 6   margin_pct    30 non-null     float64
 7   weight_kg     26 non-null     float64
 8   demand_rank   30 non-null     int64
dtypes: float64(4), int64(1), str(4)
memory usage: 2.2 KB

In [51]:
df.head(30)

,product_id,product_name,category,supplier,cost_price,sell_price,margin_pct,weight_kg,demand_rank
0,P001,Wireless Earbuds Pro,Audio,Novatech Supply,14.0,49.99,72.0,0.15,1
1,P002,Bluetooth Speaker Mini,Audio,NovaTech Supply,18.0,59.99,70.0,0.40,1
2,P003,Smart Watch Fitness,Wearables,Nova Tech Supply,55.0,139.99,60.7,0.08,1
3,P004,Smart Plug 4-Pack,Smart Home,novatech supply,11.0,34.99,68.6,0.25,2
4,P005,USB-C Hub 7-in-1,Accessories,TechCore Ltd,9.5,34.99,72.8,NaN,1
5,P006,Laptop Stand Aluminium,Accessories,TechCore Ltd,12.0,39.99,70.0,0.80,1
6,P007,Webcam 1080p HD,Peripherals,TechCore Ltd,20.0,54.99,63.6,0.30,1
7,P008,Power Bank 20000mAh,Accessories,Techcore Ltd,15.0,11.71,66.7,0.45,1
8,P009,Desk Pad XL,Accessories,TechCore Ltd,10.0,29.99,66.7,0.60,2
9,P010,Noise Cancel Headphones,Audio,TechCore Ltd,48.0,38.98,63.1,0.28,2
10,P011,Mechanical Keyboard TKL,Peripherals,EliteComponents,35.0,89.99,61.1,NaN,1
11,P012,Gaming Mouse RGB,Peripherals,Elite components,-17.0,44.99,62.2,0.18,1
12,P013,Portable SSD 1TB,Storage,EliteComponents,40.0,89.99,55.6,NaN,2
13,P014,Docking Station USB-C,Accessories,EliteComponents,45.0,109.99,59.1,0.55,2
14,P015,Microphone USB Condenser,Audio,Elite Components,42.0,99.99,58.0,0.55,3
15,P016,27in Monitor 4K,Displays,BrightGadgets,138.0,319.99,56.9,6.50,2
16,P017,Smart LED Desk Lamp,Lighting,BrightGadgets,14.0,42.99,67.4,0.90,3
17,P018,Action Camera 4K,Cameras,Bright gadgets,72.0,169.99,57.6,0.35,3
18,P019,Ring Light 10in,Lighting,BrightGadgets,19.0,54.99,65.4,1.20,3
19,P020,Laptop Cooling Pad,Accessories,BrightGadgets,11.0,32.99,66.7,0.70,3
20,P021,VR Headset Standalone,Gaming,brightgadgets,140.0,299.99,53.3,NaN,4
21,P022,Laptop Sleeve 15in,Accessories,ValueSource Co,6.0,19.99,70.0,0.25,3
22,P023,Cable Management Kit,Accessories,ValueSource Co,3.8,12.99,70.7,0.30,3
23,P024,Phone Stand Adjustable,Accessories,Value Source Co,2.8,9.99,72.0,0.15,2
24,P025,Screen Cleaning Kit,Accessories,ValueSource Co,1.5,7.99,81.2,0.10,2
25,P026,HDMI Cable 2m,Accessories,ValueSource Co,2.2,8.99,75.5,0.08,2
26,P027,Cable Clips Pack 50,Accessories,ValueSource Co,1.0,5.99,83.3,0.08,3
27,P028,Gaming Chair Ergonomic,Furniture,ValueSource Co,155.0,349.99,55.7,18.00,4
28,P029,Thermal Paste Premium,PC Parts,EliteComponents,3.0,9.99,70.0,0.05,4
29,P030,Webcam 4K Pro,Peripherals,TechCore Ltd,58.0,149.99,61.3,0.35,3

In [69]:
supplier_map = {
    'Novatech Supply': 'NovaTech Supply',
    'Nova Tech Supply': 'NovaTech Supply',
    'novatech supply': 'NovaTech Supply',
    'Techcore Ltd': 'TechCore Ltd',
    'Elite components': 'EliteComponents',
    'Bright gadgets': 'BrightGadgets',
    'brightgadgets': 'BrightGadgets',
    'Value Source Co': 'ValueSource Co'
}

df['supplier'] = df['supplier'].replace(supplier_map)
df['supplier'].value_counts()

supplier
TechCore Ltd       7
ValueSource Co     7
BrightGadgets      6
EliteComponents    5
NovaTech Supply    3
Name: count, dtype: int64

In [70]:
df.head(30)

,product_id,product_name,category,supplier,cost_price,sell_price,margin_pct,weight_kg,demand_rank
0,P001,Wireless Earbuds Pro,Audio,NovaTech Supply,14.0,49.99,72.000000,0.15,1
1,P002,Bluetooth Speaker Mini,Audio,NaN,18.0,59.99,70.000000,0.40,1
2,P003,Smart Watch Fitness,Wearables,NovaTech Supply,55.0,139.99,60.700000,0.08,1
3,P004,Smart Plug 4-Pack,Smart Home,NovaTech Supply,11.0,34.99,68.600000,0.25,2
4,P005,USB-C Hub 7-in-1,Accessories,TechCore Ltd,9.5,34.99,72.800000,NaN,1
5,P006,Laptop Stand Aluminium,Accessories,TechCore Ltd,12.0,39.99,70.000000,0.80,1
6,P007,Webcam 1080p HD,Peripherals,TechCore Ltd,20.0,54.99,63.600000,0.30,1
7,P008,Power Bank 20000mAh,Accessories,TechCore Ltd,15.0,11.71,66.700000,0.45,1
8,P009,Desk Pad XL,Accessories,TechCore Ltd,10.0,29.99,66.700000,0.60,2
9,P010,Noise Cancel Headphones,Audio,TechCore Ltd,48.0,38.98,63.100000,0.28,2
10,P011,Mechanical Keyboard TKL,Peripherals,EliteComponents,35.0,89.99,61.100000,NaN,1
11,P012,Gaming Mouse RGB,Peripherals,EliteComponents,17.0,44.99,62.213825,0.18,1
12,P013,Portable SSD 1TB,Storage,EliteComponents,40.0,89.99,55.600000,NaN,2
13,P014,Docking Station USB-C,Accessories,EliteComponents,45.0,109.99,59.100000,0.55,2
14,P015,Microphone USB Condenser,Audio,NaN,42.0,99.99,58.000000,0.55,3
15,P016,27in Monitor 4K,Displays,BrightGadgets,138.0,319.99,56.900000,6.50,2
16,P017,Smart LED Desk Lamp,Lighting,BrightGadgets,14.0,42.99,67.400000,0.90,3
17,P018,Action Camera 4K,Cameras,BrightGadgets,72.0,169.99,57.600000,0.35,3
18,P019,Ring Light 10in,Lighting,BrightGadgets,19.0,54.99,65.400000,1.20,3
19,P020,Laptop Cooling Pad,Accessories,BrightGadgets,11.0,32.99,66.700000,0.70,3
20,P021,VR Headset Standalone,Gaming,BrightGadgets,140.0,299.99,53.300000,NaN,4
21,P022,Laptop Sleeve 15in,Accessories,ValueSource Co,6.0,19.99,70.000000,0.25,3
22,P023,Cable Management Kit,Accessories,ValueSource Co,3.8,12.99,70.700000,0.30,3
23,P024,Phone Stand Adjustable,Accessories,ValueSource Co,2.8,9.99,72.000000,0.15,2
24,P025,Screen Cleaning Kit,Accessories,ValueSource Co,1.5,7.99,81.200000,0.10,2
25,P026,HDMI Cable 2m,Accessories,ValueSource Co,2.2,8.99,75.500000,0.08,2
26,P027,Cable Clips Pack 50,Accessories,ValueSource Co,1.0,5.99,83.300000,0.08,3
27,P028,Gaming Chair Ergonomic,Furniture,ValueSource Co,155.0,349.99,55.700000,18.00,4
28,P029,Thermal Paste Premium,PC Parts,EliteComponents,3.0,9.99,70.000000,0.05,4
29,P030,Webcam 4K Pro,Peripherals,TechCore Ltd,58.0,149.99,61.300000,0.35,3

In [71]:
df['product_name'] = df['product_name'].str.strip()
df['product_name'].isna().sum()
df['product_name'].duplicated().sum()

np.int64(0)

In [72]:
df['product_name']

0         Wireless Earbuds Pro
1       Bluetooth Speaker Mini
2          Smart Watch Fitness
3            Smart Plug 4-Pack
4             USB-C Hub 7-in-1
5       Laptop Stand Aluminium
6              Webcam 1080p HD
7          Power Bank 20000mAh
8                  Desk Pad XL
9      Noise Cancel Headphones
10     Mechanical Keyboard TKL
11            Gaming Mouse RGB
12            Portable SSD 1TB
13       Docking Station USB-C
14    Microphone USB Condenser
15             27in Monitor 4K
16         Smart LED Desk Lamp
17            Action Camera 4K
18             Ring Light 10in
19          Laptop Cooling Pad
20       VR Headset Standalone
21          Laptop Sleeve 15in
22        Cable Management Kit
23      Phone Stand Adjustable
24         Screen Cleaning Kit
25               HDMI Cable 2m
26         Cable Clips Pack 50
27      Gaming Chair Ergonomic
28       Thermal Paste Premium
29               Webcam 4K Pro
Name: product_name, dtype: str

In [73]:
df['category'] = df['category'].str.strip()
df['category'].value_counts()

category
Accessories    12
Audio           4
Peripherals     4
Lighting        2
Wearables       1
Smart Home      1
Storage         1
Displays        1
Cameras         1
Gaming          1
Furniture       1
PC Parts        1
Name: count, dtype: int64

In [74]:
df['cost_price'].describe()
df[df['cost_price'] <= 0]

Empty DataFrame
Columns: [product_id, product_name, category, supplier, cost_price, sell_price, margin_pct, weight_kg, demand_rank]
Index: []

In [75]:
df.loc[df['product_id'] == 'P012', 'cost_price'] = 17.0

In [76]:
mask = df['product_id'] == 'P012'
df.loc[mask, 'margin_pct'] = ((df.loc[mask, 'sell_price'] - df.loc[mask, 'cost_price']) / df.loc[mask, 'sell_price']) * 100

In [80]:
df.head(30)

,product_id,product_name,category,supplier,cost_price,sell_price,margin_pct,weight_kg,demand_rank
0,P001,Wireless Earbuds Pro,Audio,NovaTech Supply,14.0,49.99,72.000000,0.15,1
1,P002,Bluetooth Speaker Mini,Audio,NovaTech Supply,18.0,59.99,70.000000,0.40,1
2,P003,Smart Watch Fitness,Wearables,NovaTech Supply,55.0,139.99,60.700000,0.08,1
3,P004,Smart Plug 4-Pack,Smart Home,NovaTech Supply,11.0,34.99,68.600000,0.25,2
4,P005,USB-C Hub 7-in-1,Accessories,TechCore Ltd,9.5,34.99,72.800000,NaN,1
5,P006,Laptop Stand Aluminium,Accessories,TechCore Ltd,12.0,39.99,70.000000,0.80,1
6,P007,Webcam 1080p HD,Peripherals,TechCore Ltd,20.0,54.99,63.600000,0.30,1
7,P008,Power Bank 20000mAh,Accessories,TechCore Ltd,15.0,11.71,66.700000,0.45,1
8,P009,Desk Pad XL,Accessories,TechCore Ltd,10.0,29.99,66.700000,0.60,2
9,P010,Noise Cancel Headphones,Audio,TechCore Ltd,48.0,38.98,63.100000,0.28,2
10,P011,Mechanical Keyboard TKL,Peripherals,EliteComponents,35.0,89.99,61.100000,NaN,1
11,P012,Gaming Mouse RGB,Peripherals,EliteComponents,17.0,44.99,62.213825,0.18,1
12,P013,Portable SSD 1TB,Storage,EliteComponents,40.0,89.99,55.600000,NaN,2
13,P014,Docking Station USB-C,Accessories,EliteComponents,45.0,109.99,59.100000,0.55,2
14,P015,Microphone USB Condenser,Audio,NovaTech Supply,42.0,99.99,58.000000,0.55,3
15,P016,27in Monitor 4K,Displays,BrightGadgets,138.0,319.99,56.900000,6.50,2
16,P017,Smart LED Desk Lamp,Lighting,BrightGadgets,14.0,42.99,67.400000,0.90,3
17,P018,Action Camera 4K,Cameras,BrightGadgets,72.0,169.99,57.600000,0.35,3
18,P019,Ring Light 10in,Lighting,BrightGadgets,19.0,54.99,65.400000,1.20,3
19,P020,Laptop Cooling Pad,Accessories,BrightGadgets,11.0,32.99,66.700000,0.70,3
20,P021,VR Headset Standalone,Gaming,BrightGadgets,140.0,299.99,53.300000,NaN,4
21,P022,Laptop Sleeve 15in,Accessories,ValueSource Co,6.0,19.99,70.000000,0.25,3
22,P023,Cable Management Kit,Accessories,ValueSource Co,3.8,12.99,70.700000,0.30,3
23,P024,Phone Stand Adjustable,Accessories,ValueSource Co,2.8,9.99,72.000000,0.15,2
24,P025,Screen Cleaning Kit,Accessories,ValueSource Co,1.5,7.99,81.200000,0.10,2
25,P026,HDMI Cable 2m,Accessories,ValueSource Co,2.2,8.99,75.500000,0.08,2
26,P027,Cable Clips Pack 50,Accessories,ValueSource Co,1.0,5.99,83.300000,0.08,3
27,P028,Gaming Chair Ergonomic,Furniture,ValueSource Co,155.0,349.99,55.700000,18.00,4
28,P029,Thermal Paste Premium,PC Parts,EliteComponents,3.0,9.99,70.000000,0.05,4
29,P030,Webcam 4K Pro,Peripherals,TechCore Ltd,58.0,149.99,61.300000,0.35,3

In [81]:
df.loc[df['product_id'] == 'P002', 'supplier'] = 'NovaTech Supply'
df.loc[df['product_id'] == 'P015', 'supplier'] = 'NovaTech Supply'

In [85]:
((df['sell_price'] - df['cost_price']) / df['sell_price']) * 100

0     71.994399
1     69.994999
2     60.711479
3     68.562446
4     72.849386
5     69.992498
6     63.629751
7    -28.095645
8     66.655552
9    -23.140072
10    61.106790
11    62.213825
12    55.550617
13    59.087190
14    57.995800
15    56.873652
16    67.434287
17    57.644567
18    65.448263
19    66.656563
20    53.331778
21    69.984992
22    70.746728
23    71.971972
24    81.226533
25    75.528365
26    83.305509
27    55.713020
28    69.969970
29    61.330755
dtype: float64

In [87]:
df['margin_pct'] = (((df['sell_price'] - df['cost_price']) / df['sell_price']) * 100).round(2)

In [89]:
((df['sell_price'] - df['cost_price']) / df['sell_price']) * 100

0     71.994399
1     69.994999
2     60.711479
3     68.562446
4     72.849386
5     69.992498
6     63.629751
7    -28.095645
8     66.655552
9    -23.140072
10    61.106790
11    62.213825
12    55.550617
13    59.087190
14    57.995800
15    56.873652
16    67.434287
17    57.644567
18    65.448263
19    66.656563
20    53.331778
21    69.984992
22    70.746728
23    71.971972
24    81.226533
25    75.528365
26    83.305509
27    55.713020
28    69.969970
29    61.330755
dtype: float64

In [96]:
df['margin_pct'].describe()
df[df['margin_pct'] < 0]

,product_id,product_name,category,supplier,cost_price,sell_price,margin_pct,weight_kg,demand_rank
7,P008,Power Bank 20000mAh,Accessories,TechCore Ltd,15.0,11.71,-28.095645,0.45,1
9,P010,Noise Cancel Headphones,Audio,TechCore Ltd,48.0,38.98,-23.140072,0.28,2

In [94]:
mask = df['product_id'].isin(['P008', 'P010'])
df.loc[mask, 'margin_pct'] = ((df.loc[mask, 'sell_price'] - df.loc[mask, 'cost_price']) / df.loc[mask, 'sell_price']) * 100

In [98]:
df['margin_pct'] = ((df['sell_price'] - df['cost_price']) / df['sell_price']) * 100

In [102]:
df['weight_kg'].isna().sum()
df[df['weight_kg'] <= 0]

Empty DataFrame
Columns: [product_id, product_name, category, supplier, cost_price, sell_price, margin_pct, weight_kg, demand_rank]
Index: []

In [104]:
df['demand_rank'].isna().sum()
df['demand_rank'].value_counts()

demand_rank
1    9
2    9
3    9
4    3
Name: count, dtype: int64

In [110]:
df.head(30)

,product_id,product_name,category,supplier,cost_price,sell_price,margin_pct,weight_kg,demand_rank
0,P001,Wireless Earbuds Pro,Audio,NovaTech Supply,14.0,49.99,71.994399,0.15,1
1,P002,Bluetooth Speaker Mini,Audio,NovaTech Supply,18.0,59.99,69.994999,0.40,1
2,P003,Smart Watch Fitness,Wearables,NovaTech Supply,55.0,139.99,60.711479,0.08,1
3,P004,Smart Plug 4-Pack,Smart Home,NovaTech Supply,11.0,34.99,68.562446,0.25,2
4,P005,USB-C Hub 7-in-1,Accessories,TechCore Ltd,9.5,34.99,72.849386,0.22,1
5,P006,Laptop Stand Aluminium,Accessories,TechCore Ltd,12.0,39.99,69.992498,0.80,1
6,P007,Webcam 1080p HD,Peripherals,TechCore Ltd,20.0,54.99,63.629751,0.30,1
7,P008,Power Bank 20000mAh,Accessories,TechCore Ltd,15.0,11.71,-28.095645,0.45,1
8,P009,Desk Pad XL,Accessories,TechCore Ltd,10.0,29.99,66.655552,0.60,2
9,P010,Noise Cancel Headphones,Audio,TechCore Ltd,48.0,38.98,-23.140072,0.28,2
10,P011,Mechanical Keyboard TKL,Peripherals,EliteComponents,35.0,89.99,61.106790,0.80,1
11,P012,Gaming Mouse RGB,Peripherals,EliteComponents,17.0,44.99,62.213825,0.18,1
12,P013,Portable SSD 1TB,Storage,EliteComponents,40.0,89.99,55.550617,0.30,2
13,P014,Docking Station USB-C,Accessories,EliteComponents,45.0,109.99,59.087190,0.55,2
14,P015,Microphone USB Condenser,Audio,NovaTech Supply,42.0,99.99,57.995800,0.55,3
15,P016,27in Monitor 4K,Displays,BrightGadgets,138.0,319.99,56.873652,6.50,2
16,P017,Smart LED Desk Lamp,Lighting,BrightGadgets,14.0,42.99,67.434287,0.90,3
17,P018,Action Camera 4K,Cameras,BrightGadgets,72.0,169.99,57.644567,0.35,3
18,P019,Ring Light 10in,Lighting,BrightGadgets,19.0,54.99,65.448263,1.20,3
19,P020,Laptop Cooling Pad,Accessories,BrightGadgets,11.0,32.99,66.656563,0.70,3
20,P021,VR Headset Standalone,Gaming,BrightGadgets,140.0,299.99,53.331778,0.95,4
21,P022,Laptop Sleeve 15in,Accessories,ValueSource Co,6.0,19.99,69.984992,0.25,3
22,P023,Cable Management Kit,Accessories,ValueSource Co,3.8,12.99,70.746728,0.30,3
23,P024,Phone Stand Adjustable,Accessories,ValueSource Co,2.8,9.99,71.971972,0.15,2
24,P025,Screen Cleaning Kit,Accessories,ValueSource Co,1.5,7.99,81.226533,0.10,2
25,P026,HDMI Cable 2m,Accessories,ValueSource Co,2.2,8.99,75.528365,0.08,2
26,P027,Cable Clips Pack 50,Accessories,ValueSource Co,1.0,5.99,83.305509,0.08,3
27,P028,Gaming Chair Ergonomic,Furniture,ValueSource Co,155.0,349.99,55.713020,18.00,4
28,P029,Thermal Paste Premium,PC Parts,EliteComponents,3.0,9.99,69.969970,0.05,4
29,P030,Webcam 4K Pro,Peripherals,TechCore Ltd,58.0,149.99,61.330755,0.35,3

In [111]:
# Export to CSV
df.to_csv("product_data_cleaned.csv", index=False)
print("Exported to product_data_cleaned.csv")

# Verify in pandas
df_exported = pd.read_csv("product_data_cleaned.csv")
df_exported.head(10)

Exported to product_data_cleaned.csv

,product_id,product_name,category,supplier,cost_price,sell_price,margin_pct,weight_kg,demand_rank
0,P001,Wireless Earbuds Pro,Audio,NovaTech Supply,14.0,49.99,71.994399,0.15,1
1,P002,Bluetooth Speaker Mini,Audio,NovaTech Supply,18.0,59.99,69.994999,0.40,1
2,P003,Smart Watch Fitness,Wearables,NovaTech Supply,55.0,139.99,60.711479,0.08,1
3,P004,Smart Plug 4-Pack,Smart Home,NovaTech Supply,11.0,34.99,68.562446,0.25,2
4,P005,USB-C Hub 7-in-1,Accessories,TechCore Ltd,9.5,34.99,72.849386,0.22,1
5,P006,Laptop Stand Aluminium,Accessories,TechCore Ltd,12.0,39.99,69.992498,0.80,1
6,P007,Webcam 1080p HD,Peripherals,TechCore Ltd,20.0,54.99,63.629751,0.30,1
7,P008,Power Bank 20000mAh,Accessories,TechCore Ltd,15.0,11.71,-28.095645,0.45,1
8,P009,Desk Pad XL,Accessories,TechCore Ltd,10.0,29.99,66.655552,0.60,2
9,P010,Noise Cancel Headphones,Audio,TechCore Ltd,48.0,38.98,-23.140072,0.28,2