In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('date_dim.csv')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1096 entries, 0 to 1095
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   date            1096 non-null   str
 1   year            1096 non-null   int64
 2   quarter         1096 non-null   str
 3   month_num       1096 non-null   int64
 4   month_name      1096 non-null   str
 5   week_num        1096 non-null   int64
 6   day_of_week     1096 non-null   str
 7   is_weekend      1096 non-null   bool
 8   is_month_end    1096 non-null   bool
 9   is_peak_season  1096 non-null   bool
 10  season          1096 non-null   str
dtypes: bool(3), int64(3), str(5)
memory usage: 71.8 KB

In [8]:
df.head(30)

,date,year,quarter,month_num,month_name,week_num,day_of_week,is_weekend,is_month_end,is_peak_season,season
0,2022-01-01,2022,Q1,1,January,52,Saturday,True,False,False,Winter
1,2022-01-02,2022,Q1,1,January,52,Sunday,True,False,False,Winter
2,2022-01-03,2022,Q1,1,January,1,Monday,False,False,False,Winter
3,2022-01-04,2022,Q1,1,January,1,Tuesday,False,False,False,Winter
4,2022-01-05,2022,Q1,1,January,1,Wednesday,False,False,False,Winter
5,2022-01-06,2022,Q1,1,January,1,Thursday,False,False,False,Winter
6,2022-01-07,2022,Q1,1,January,1,Friday,False,False,False,Winter
7,2022-01-08,2022,Q1,1,January,1,Saturday,True,False,False,Winter
8,2022-01-09,2022,Q1,1,January,1,Sunday,True,False,False,Winter
9,2022-01-10,2022,Q1,1,January,2,Monday,False,False,False,Winter
10,2022-01-11,2022,Q1,1,January,2,Tuesday,False,False,False,Winter
11,2022-01-12,2022,Q1,1,January,2,Wednesday,False,False,False,Winter
12,2022-01-13,2022,Q1,1,January,2,Thursday,False,False,False,Winter
13,2022-01-14,2022,Q1,1,January,2,Friday,False,False,False,Winter
14,2022-01-15,2022,Q1,1,January,2,Saturday,True,False,False,Winter
15,2022-01-16,2022,Q1,1,January,2,Sunday,True,False,False,Winter
16,2022-01-17,2022,Q1,1,January,3,Monday,False,False,False,Winter
17,2022-01-18,2022,Q1,1,January,3,Tuesday,False,False,False,Winter
18,2022-01-19,2022,Q1,1,January,3,Wednesday,False,False,False,Winter
19,2022-01-20,2022,Q1,1,January,3,Thursday,False,False,False,Winter
20,2022-01-21,2022,Q1,1,January,3,Friday,False,False,False,Winter
21,2022-01-22,2022,Q1,1,January,3,Saturday,True,False,False,Winter
22,2022-01-23,2022,Q1,1,January,3,Sunday,True,False,False,Winter
23,2022-01-24,2022,Q1,1,January,4,Monday,False,True,False,Winter
24,2022-01-25,2022,Q1,1,January,4,Tuesday,False,True,False,Winter
25,2022-01-26,2022,Q1,1,January,4,Wednesday,False,True,False,Winter
26,2022-01-27,2022,Q1,1,January,4,Thursday,False,True,False,Winter
27,2022-01-28,2022,Q1,1,January,4,Friday,False,True,False,Winter
28,2022-01-29,2022,Q1,1,January,4,Saturday,True,True,False,Winter
29,2022-01-30,2022,Q1,1,January,4,Sunday,True,True,False,Winter

In [11]:
# Convert to datetime
df['date'] = pd.to_datetime(df['date'])

# Check results
print(f"Data type: {df['date'].dtype}")
print(f"Non-null count: {df['date'].notnull().sum()}")
print(f"Min date: {df['date'].min()}")
print(f"Max date: {df['date'].max()}")
print(f"First 5 values:\n{df['date'].head()}")

Data type: datetime64[us]
Non-null count: 1096
Min date: 2022-01-01 00:00:00
Max date: 2024-12-31 00:00:00
First 5 values:
0   2022-01-01
1   2022-01-02
2   2022-01-03
3   2022-01-04
4   2022-01-05
Name: date, dtype: datetime64[us]

In [13]:
# Verify year matches date
year_from_date = df['date'].dt.year
year_mismatch = df['year'] != year_from_date

print(f"Data type: {df['year'].dtype}")
print(f"Non-null count: {df['year'].notnull().sum()}")
print(f"Unique years: {df['year'].unique()}")
print(f"Year value counts:\n{df['year'].value_counts().sort_index()}")
print(f"\nYears mismatching date: {year_mismatch.sum()}")

if year_mismatch.sum() > 0:
    print("\nMISMATCHED ROWS:")
    print(df[year_mismatch][['date', 'year']])
else:
    print("\n✓ All years match the date column!")

Data type: int64
Non-null count: 1096
Unique years: [2022 2023 2024]
Year value counts:
year
2022    365
2023    365
2024    366
Name: count, dtype: int64

Years mismatching date: 0

✓ All years match the date column!

In [15]:
#Verify quarter matches date
quarter_from_date = df['date'].dt.quarter.map(lambda x: f'Q{x}')
quarter_mismatch = df['quarter'] != quarter_from_date

print(f"Data type: {df['quarter'].dtype}")
print(f"Non-null count: {df['quarter'].notnull().sum()}")
print(f"Unique quarters: {df['quarter'].unique()}")
print(f"\nQuarter value counts:\n{df['quarter'].value_counts()}")
print(f"\nQuarters mismatching date: {quarter_mismatch.sum()}")

if quarter_mismatch.sum() > 0:
    print("\nMISMATCHED ROWS:")
    print(df[quarter_mismatch][['date', 'quarter']].head(10))
else:
    print("\n✓ All quarters match the date column!")

Data type: str
Non-null count: 1096
Unique quarters: <StringArray>
['Q1', 'Q2', 'Q3', 'Q4']
Length: 4, dtype: str

Quarter value counts:
quarter
Q3    276
Q4    276
Q2    273
Q1    271
Name: count, dtype: int64

Quarters mismatching date: 0

✓ All quarters match the date column!

In [17]:
# Verify month_num matches date
month_from_date = df['date'].dt.month
month_mismatch = df['month_num'] != month_from_date

print(f"Data type: {df['month_num'].dtype}")
print(f"Non-null count: {df['month_num'].notnull().sum()}")
print(f"Unique values: {sorted(df['month_num'].unique())}")
print(f"\nMonth number value counts:\n{df['month_num'].value_counts().sort_index()}")
print(f"\nMonths mismatching date: {month_mismatch.sum()}")

if month_mismatch.sum() > 0:
    print("\nMISMATCHED ROWS:")
    print(df[month_mismatch][['date', 'month_num']].head(10))
else:
    print("\n✓ All month_num values match the date column!")

Data type: int64
Non-null count: 1096
Unique values: [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]

Month number value counts:
month_num
1     93
2     85
3     93
4     90
5     93
6     90
7     93
8     93
9     90
10    93
11    90
12    93
Name: count, dtype: int64

Months mismatching date: 0

✓ All month_num values match the date column!

In [19]:
# Verify month_name matches date
month_name_from_date = df['date'].dt.month_name()
month_name_mismatch = df['month_name'] != month_name_from_date

print(f"Data type: {df['month_name'].dtype}")
print(f"Non-null count: {df['month_name'].notnull().sum()}")
print(f"Unique values: {sorted(df['month_name'].unique())}")
print(f"\nMonth name value counts:\n{df['month_name'].value_counts()}")
print(f"\nMonth names mismatching date: {month_name_mismatch.sum()}")

if month_name_mismatch.sum() > 0:
    print("\nMISMATCHED ROWS:")
    print(df[month_name_mismatch][['date', 'month_name']].head(10))
else:
    print("\n✓ All month_name values match the date column!")

Data type: str
Non-null count: 1096
Unique values: ['April', 'August', 'December', 'February', 'January', 'July', 'June', 'March', 'May', 'November', 'October', 'September']

Month name value counts:
month_name
January      93
March        93
May          93
July         93
August       93
October      93
December     93
April        90
June         90
September    90
November     90
February     85
Name: count, dtype: int64

Month names mismatching date: 0

✓ All month_name values match the date column!

In [21]:
# Verify week_num matches ISO week number
week_from_date = df['date'].dt.isocalendar().week
week_mismatch = df['week_num'] != week_from_date

print(f"Data type: {df['week_num'].dtype}")
print(f"Non-null count: {df['week_num'].notnull().sum()}")
print(f"Week range: {df['week_num'].min()} to {df['week_num'].max()}")
print(f"\nWeek number value counts (first 10):\n{df['week_num'].value_counts().sort_index().head(10)}")
print(f"\nWeeks mismatching date: {week_mismatch.sum()}")

if week_mismatch.sum() > 0:
    print("\nMISMATCHED ROWS (first 10):")
    print(df[week_mismatch][['date', 'week_num']].head(10))
else:
    print("\n✓ All week_num values match the date column!")

Data type: int64
Non-null count: 1096
Week range: 1 to 52

Week number value counts (first 10):
week_num
1     23
2     21
3     21
4     21
5     21
6     21
7     21
8     21
9     21
10    21
Name: count, dtype: int64

Weeks mismatching date: 0

✓ All week_num values match the date column!

In [23]:
# Verify day_of_week matches date
day_from_date = df['date'].dt.day_name()
day_mismatch = df['day_of_week'] != day_from_date

print(f"Data type: {df['day_of_week'].dtype}")
print(f"Non-null count: {df['day_of_week'].notnull().sum()}")
print(f"Unique values: {sorted(df['day_of_week'].unique())}")
print(f"\nDay of week value counts:\n{df['day_of_week'].value_counts()}")
print(f"\nDays mismatching date: {day_mismatch.sum()}")

if day_mismatch.sum() > 0:
    print("\nMISMATCHED ROWS:")
    print(df[day_mismatch][['date', 'day_of_week']].head(10))
else:
    print("\n✓ All day_of_week values match the date column!")

Data type: str
Non-null count: 1096
Unique values: ['Friday', 'Monday', 'Saturday', 'Sunday', 'Thursday', 'Tuesday', 'Wednesday']

Day of week value counts:
day_of_week
Saturday     157
Sunday       157
Monday       157
Tuesday      157
Wednesday    156
Thursday     156
Friday       156
Name: count, dtype: int64

Days mismatching date: 0

✓ All day_of_week values match the date column!

In [25]:
# Verify is_weekend matches date (Saturday=5, Sunday=6)
is_weekend_verified = df['date'].dt.dayofweek >= 5
is_weekend_mismatch = df['is_weekend'] != is_weekend_verified

print(f"Data type: {df['is_weekend'].dtype}")
print(f"Non-null count: {df['is_weekend'].notnull().sum()}")
print(f"Value counts:\n{df['is_weekend'].value_counts()}")
print(f"\nTrue count (weekend): {df['is_weekend'].sum()}")
print(f"False count (weekday): {len(df) - df['is_weekend'].sum()}")
print(f"\nValues mismatching date: {is_weekend_mismatch.sum()}")

if is_weekend_mismatch.sum() > 0:
    print("\nMISMATCHED ROWS:")
    print(df[is_weekend_mismatch][['date', 'day_of_week', 'is_weekend']].head(10))
else:
    print("\n✓ All is_weekend values match the date column!")

Data type: bool
Non-null count: 1096
Value counts:
is_weekend
False    782
True     314
Name: count, dtype: int64

True count (weekend): 314
False count (weekday): 782

Values mismatching date: 0

✓ All is_weekend values match the date column!

In [27]:
# Verify is_month_end matches date
is_month_end_verified = df['date'].dt.is_month_end
is_month_end_mismatch = df['is_month_end'] != is_month_end_verified

print(f"Data type: {df['is_month_end'].dtype}")
print(f"Non-null count: {df['is_month_end'].notnull().sum()}")
print(f"Value counts:\n{df['is_month_end'].value_counts()}")
print(f"\nTrue count (month end): {df['is_month_end'].sum()}")
print(f"False count: {len(df) - df['is_month_end'].sum()}")
print(f"\nMonths end mismatching date: {is_month_end_mismatch.sum()}")

if is_month_end_mismatch.sum() > 0:
    print("\nMISMATCHED ROWS:")
    print(df[is_month_end_mismatch][['date', 'is_month_end']].head(10))
else:
    print("\n✓ All is_month_end values match the date column!")

Data type: bool
Non-null count: 1096
Value counts:
is_month_end
False    828
True     268
Name: count, dtype: int64

True count (month end): 268
False count: 828

Months end mismatching date: 232

MISMATCHED ROWS:
         date  is_month_end
23 2022-01-24          True
24 2022-01-25          True
25 2022-01-26          True
26 2022-01-27          True
27 2022-01-28          True
28 2022-01-29          True
29 2022-01-30          True
54 2022-02-24          True
55 2022-02-25          True
56 2022-02-26          True

In [29]:
# Fix: Standard pandas is_month_end (only last day of month)
df['is_month_end'] = df['date'].dt.is_month_end

print(f"Fixed is_month_end value counts:\n{df['is_month_end'].value_counts()}")
print(f"True count (month end): {df['is_month_end'].sum()}")
print(f"\nLast day of each month (first 12):")
print(df[df['is_month_end'] == True][['date', 'month_name']].head(12))

Fixed is_month_end value counts:
is_month_end
False    1060
True       36
Name: count, dtype: int64
True count (month end): 36

Last day of each month (first 12):
          date month_name
30  2022-01-31    January
58  2022-02-28   February
89  2022-03-31      March
119 2022-04-30      April
150 2022-05-31        May
180 2022-06-30       June
211 2022-07-31       July
242 2022-08-31     August
272 2022-09-30  September
303 2022-10-31    October
333 2022-11-30   November
364 2022-12-31   December

In [30]:
print(f"Data type: {df['is_peak_season'].dtype}")
print(f"Non-null count: {df['is_peak_season'].notnull().sum()}")
print(f"Value counts:\n{df['is_peak_season'].value_counts()}")
print(f"\nTrue count (peak season): {df['is_peak_season'].sum()}")
print(f"False count: {len(df) - df['is_peak_season'].sum()}")

if df['is_peak_season'].sum() > 0:
    print(f"\nPeak season by month:")
    print(df[df['is_peak_season'] == True]['month_name'].value_counts())
    print(f"\nPeak season by season:")
    print(df[df['is_peak_season'] == True]['season'].value_counts())
else:
    print("\nNote: No peak season days marked in this dataset.")
    print("You may need to define which months/seasons are 'peak' for your business.")

Data type: bool
Non-null count: 1096
Value counts:
is_peak_season
False    913
True     183
Name: count, dtype: int64

True count (peak season): 183
False count: 913

Peak season by month:
month_name
December    93
November    90
Name: count, dtype: int64

Peak season by season:
season
Winter    93
Autumn    90
Name: count, dtype: int64

In [32]:
# Define expected season based on month
def get_expected_season(month):
    if month in [12, 1, 2]:
        return 'Winter'
    elif month in [3, 4, 5]:
        return 'Spring'
    elif month in [6, 7, 8]:
        return 'Summer'
    else:  # 9, 10, 11
        return 'Autumn'

season_verified = df['month_num'].apply(get_expected_season)
season_mismatch = df['season'] != season_verified

print(f"Data type: {df['season'].dtype}")
print(f"Non-null count: {df['season'].notnull().sum()}")
print(f"Unique values: {sorted(df['season'].unique())}")
print(f"\nSeason value counts:\n{df['season'].value_counts()}")
print(f"\nSeasons mismatching date: {season_mismatch.sum()}")

if season_mismatch.sum() > 0:
    print("\nMISMATCHED ROWS:")
    print(df[season_mismatch][['date', 'month_num', 'season']].head(10))
else:
    print("\n✓ All season values match the month_num column!")

Data type: str
Non-null count: 1096
Unique values: ['Autumn', 'Spring', 'Summer', 'Winter']

Season value counts:
season
Spring    276
Summer    276
Autumn    273
Winter    271
Name: count, dtype: int64

Seasons mismatching date: 0

✓ All season values match the month_num column!

In [34]:
df.head(30)

,date,year,quarter,month_num,month_name,week_num,day_of_week,is_weekend,is_month_end,is_peak_season,season
0,2022-01-01,2022,Q1,1,January,52,Saturday,True,False,False,Winter
1,2022-01-02,2022,Q1,1,January,52,Sunday,True,False,False,Winter
2,2022-01-03,2022,Q1,1,January,1,Monday,False,False,False,Winter
3,2022-01-04,2022,Q1,1,January,1,Tuesday,False,False,False,Winter
4,2022-01-05,2022,Q1,1,January,1,Wednesday,False,False,False,Winter
5,2022-01-06,2022,Q1,1,January,1,Thursday,False,False,False,Winter
6,2022-01-07,2022,Q1,1,January,1,Friday,False,False,False,Winter
7,2022-01-08,2022,Q1,1,January,1,Saturday,True,False,False,Winter
8,2022-01-09,2022,Q1,1,January,1,Sunday,True,False,False,Winter
9,2022-01-10,2022,Q1,1,January,2,Monday,False,False,False,Winter
10,2022-01-11,2022,Q1,1,January,2,Tuesday,False,False,False,Winter
11,2022-01-12,2022,Q1,1,January,2,Wednesday,False,False,False,Winter
12,2022-01-13,2022,Q1,1,January,2,Thursday,False,False,False,Winter
13,2022-01-14,2022,Q1,1,January,2,Friday,False,False,False,Winter
14,2022-01-15,2022,Q1,1,January,2,Saturday,True,False,False,Winter
15,2022-01-16,2022,Q1,1,January,2,Sunday,True,False,False,Winter
16,2022-01-17,2022,Q1,1,January,3,Monday,False,False,False,Winter
17,2022-01-18,2022,Q1,1,January,3,Tuesday,False,False,False,Winter
18,2022-01-19,2022,Q1,1,January,3,Wednesday,False,False,False,Winter
19,2022-01-20,2022,Q1,1,January,3,Thursday,False,False,False,Winter
20,2022-01-21,2022,Q1,1,January,3,Friday,False,False,False,Winter
21,2022-01-22,2022,Q1,1,January,3,Saturday,True,False,False,Winter
22,2022-01-23,2022,Q1,1,January,3,Sunday,True,False,False,Winter
23,2022-01-24,2022,Q1,1,January,4,Monday,False,False,False,Winter
24,2022-01-25,2022,Q1,1,January,4,Tuesday,False,False,False,Winter
25,2022-01-26,2022,Q1,1,January,4,Wednesday,False,False,False,Winter
26,2022-01-27,2022,Q1,1,January,4,Thursday,False,False,False,Winter
27,2022-01-28,2022,Q1,1,January,4,Friday,False,False,False,Winter
28,2022-01-29,2022,Q1,1,January,4,Saturday,True,False,False,Winter
29,2022-01-30,2022,Q1,1,January,4,Sunday,True,False,False,Winter

In [35]:
# Export to CSV
df.to_csv("cleaned_date_dimension.csv", index=False)
print("Exported to cleaned_date_dimension.csv")


# Verify in pandas
df_exported = pd.read_csv("cleaned_date_dimension.csv")
df_exported.head(10)

Exported to cleaned_date_dimension.csv

,date,year,quarter,month_num,month_name,week_num,day_of_week,is_weekend,is_month_end,is_peak_season,season
0,2022-01-01,2022,Q1,1,January,52,Saturday,True,False,False,Winter
1,2022-01-02,2022,Q1,1,January,52,Sunday,True,False,False,Winter
2,2022-01-03,2022,Q1,1,January,1,Monday,False,False,False,Winter
3,2022-01-04,2022,Q1,1,January,1,Tuesday,False,False,False,Winter
4,2022-01-05,2022,Q1,1,January,1,Wednesday,False,False,False,Winter
5,2022-01-06,2022,Q1,1,January,1,Thursday,False,False,False,Winter
6,2022-01-07,2022,Q1,1,January,1,Friday,False,False,False,Winter
7,2022-01-08,2022,Q1,1,January,1,Saturday,True,False,False,Winter
8,2022-01-09,2022,Q1,1,January,1,Sunday,True,False,False,Winter
9,2022-01-10,2022,Q1,1,January,2,Monday,False,False,False,Winter